import { TemplateTopologyFamily } from "./types";

export const TOPOLOGY_FAMILY_LIBRARY: TemplateTopologyFamily[] = [
  {
    id: "TOPOLOGY-NARROW-2025",
    name: "20–25 FT NARROW PLOT URBAN HOME",
    description: "Optimized single-spine layout with front living & rear kitchen/bedroom for narrow plots (20-25ft frontage).",
    category: "Narrow Plot",
    minPlotWidth: 18,
    maxPlotWidth: 26,
    minPlotLength: 30,
    maxPlotLength: 60,
    supportedFacings: ["East", "West", "North", "South"],
    supportedFloors: [1, 2, 3],
    verticalCore: {
      lift: { xRatio: 0.7, yRatio: 0.5, wFt: 5.0, hFt: 5.0 },
      stair: { xRatio: 0.7, yRatio: 0.65, wFt: 7.0, hFt: 14.0, type: "Dog-Legged" },
      shaft: { xRatio: 0.9, yRatio: 0.9, wFt: 2.5, hFt: 3.0 },
    },
    vastuBaseScore: 92,
    spaceBaseScore: 95,
    ventilationBaseScore: 88,
    roomNodes: [
      { id: "liv", name: "LIVING ROOM", type: "living", minWidthFt: 11, minLengthFt: 12, minAreaSqFt: 132, preferredVastu: ["NE", "E"], connectsTo: ["din", "kit"], isOptional: false, priority: 10, stretchAxis: "both", shrinkPriority: 1 },
      { id: "din", name: "DINING AREA", type: "dining", minWidthFt: 9, minLengthFt: 9, minAreaSqFt: 81, preferredVastu: ["E", "CENTER"], connectsTo: ["liv", "kit"], isOptional: false, priority: 8, stretchAxis: "both", shrinkPriority: 2 },
      { id: "kit", name: "KITCHEN (SE)", type: "kitchen", minWidthFt: 8, minLengthFt: 9, minAreaSqFt: 72, preferredVastu: ["SE"], connectsTo: ["din", "util"], isOptional: false, priority: 9, stretchAxis: "x", shrinkPriority: 3 },
      { id: "util", name: "UTILITY", type: "utility", minWidthFt: 4, minLengthFt: 6, minAreaSqFt: 24, preferredVastu: ["SE", "S"], connectsTo: ["kit"], isOptional: false, priority: 6, stretchAxis: "none", shrinkPriority: 4 },
      { id: "bed1", name: "MASTER BEDROOM", type: "master_bedroom", minWidthFt: 10, minLengthFt: 11, minAreaSqFt: 110, preferredVastu: ["SW"], connectsTo: ["toi1"], isOptional: false, priority: 10, stretchAxis: "both", shrinkPriority: 1 },
      { id: "toi1", name: "ATTACHED TOILET", type: "attached_toilet", minWidthFt: 4.5, minLengthFt: 7, minAreaSqFt: 31.5, preferredVastu: ["W", "NW"], connectsTo: ["bed1"], isOptional: false, priority: 8, stretchAxis: "none", shrinkPriority: 5 },
    ],
  },

  {
    id: "TOPOLOGY-3040-DUPLEX",
    name: "30x40 LUXURY DUPLEX FAMILY RESIDENCE",
    description: "Standard Indian 30x40 villa plan matching Target Reference Quality with centered core & grand living foyer.",
    category: "30x40 Duplex",
    minPlotWidth: 28,
    maxPlotWidth: 34,
    minPlotLength: 36,
    maxPlotLength: 45,
    supportedFacings: ["South", "East", "North", "West"],
    supportedFloors: [2, 3, 4],
    verticalCore: {
      lift: { xRatio: 0.6, yRatio: 0.5, wFt: 5.0, hFt: 5.0 },
      stair: { xRatio: 0.75, yRatio: 0.6, wFt: 7.5, hFt: 15.0, type: "Dog-Legged" },
      shaft: { xRatio: 0.65, yRatio: 0.95, wFt: 3.0, hFt: 3.0 },
    },
    vastuBaseScore: 98,
    spaceBaseScore: 94,
    ventilationBaseScore: 95,
    roomNodes: [
      { id: "liv", name: "SPACIOUS LIVING ROOM", type: "living", minWidthFt: 14, minLengthFt: 12, minAreaSqFt: 168, preferredVastu: ["NE", "E"], connectsTo: ["din", "kit"], isOptional: false, priority: 10, stretchAxis: "both", shrinkPriority: 1 },
      { id: "din", name: "DINING HALL", type: "dining", minWidthFt: 10, minLengthFt: 10, minAreaSqFt: 100, preferredVastu: ["E", "CENTER"], connectsTo: ["liv", "kit"], isOptional: false, priority: 9, stretchAxis: "both", shrinkPriority: 2 },
      { id: "kit", name: "KITCHEN (SE AGNEYA)", type: "kitchen", minWidthFt: 10, minLengthFt: 9, minAreaSqFt: 90, preferredVastu: ["SE"], connectsTo: ["din", "util"], isOptional: false, priority: 10, stretchAxis: "x", shrinkPriority: 3 },
      { id: "util", name: "UTILITY", type: "utility", minWidthFt: 5, minLengthFt: 7, minAreaSqFt: 35, preferredVastu: ["SE", "S"], connectsTo: ["kit"], isOptional: false, priority: 7, stretchAxis: "none", shrinkPriority: 4 },
      { id: "bed1", name: "MASTER BEDROOM (SW)", type: "master_bedroom", minWidthFt: 12, minLengthFt: 12, minAreaSqFt: 144, preferredVastu: ["SW"], connectsTo: ["toi1"], isOptional: false, priority: 10, stretchAxis: "both", shrinkPriority: 1 },
      { id: "toi1", name: "ATTACHED MASTER TOILET", type: "attached_toilet", minWidthFt: 5, minLengthFt: 7, minAreaSqFt: 35, preferredVastu: ["W", "S"], connectsTo: ["bed1"], isOptional: false, priority: 8, stretchAxis: "none", shrinkPriority: 5 },
      { id: "pooja", name: "POOJA ROOM", type: "pooja", minWidthFt: 4, minLengthFt: 5, minAreaSqFt: 20, preferredVastu: ["NE", "E"], connectsTo: ["liv"], isOptional: true, priority: 8, stretchAxis: "none", shrinkPriority: 6 },
    ],
  },

  {
    id: "TOPOLOGY-3050-60-DUPLEX",
    name: "30x50 / 30x60 EXTENDED DUPLEX",
    description: "Deep plot topology with internal courtyard, expanded dining & double height living area.",
    category: "30x50/60",
    minPlotWidth: 28,
    maxPlotWidth: 35,
    minPlotLength: 46,
    maxPlotLength: 65,
    supportedFacings: ["East", "West", "North", "South"],
    supportedFloors: [2, 3, 4],
    verticalCore: {
      lift: { xRatio: 0.65, yRatio: 0.45, wFt: 5.5, hFt: 5.5 },
      stair: { xRatio: 0.75, yRatio: 0.5, wFt: 8.0, hFt: 16.0, type: "Open-Well" },
      shaft: { xRatio: 0.9, yRatio: 0.9, wFt: 3.5, hFt: 3.5 },
    },
    vastuBaseScore: 96,
    spaceBaseScore: 98,
    ventilationBaseScore: 96,
    roomNodes: [
      { id: "liv", name: "GRAND DOUBLE HEIGHT LIVING", type: "living", minWidthFt: 15, minLengthFt: 14, minAreaSqFt: 210, preferredVastu: ["NE"], connectsTo: ["din"], isOptional: false, priority: 10, stretchAxis: "both", shrinkPriority: 1 },
      { id: "din", name: "ROYAL DINING AREA", type: "dining", minWidthFt: 12, minLengthFt: 12, minAreaSqFt: 144, preferredVastu: ["E", "CENTER"], connectsTo: ["liv", "kit"], isOptional: false, priority: 9, stretchAxis: "both", shrinkPriority: 2 },
      { id: "kit", name: "MODULAR KITCHEN & PANTRY", type: "kitchen", minWidthFt: 11, minLengthFt: 10, minAreaSqFt: 110, preferredVastu: ["SE"], connectsTo: ["din", "util", "store"], isOptional: false, priority: 10, stretchAxis: "both", shrinkPriority: 3 },
      { id: "util", name: "SERVICE UTILITY", type: "utility", minWidthFt: 6, minLengthFt: 8, minAreaSqFt: 48, preferredVastu: ["SE"], connectsTo: ["kit"], isOptional: false, priority: 8, stretchAxis: "none", shrinkPriority: 4 },
      { id: "store", name: "STORE ROOM", type: "store", minWidthFt: 4, minLengthFt: 6, minAreaSqFt: 24, preferredVastu: ["S"], connectsTo: ["kit"], isOptional: true, priority: 6, stretchAxis: "none", shrinkPriority: 5 },
      { id: "bed1", name: "MASTER BEDROOM SUITE", type: "master_bedroom", minWidthFt: 13, minLengthFt: 14, minAreaSqFt: 182, preferredVastu: ["SW"], connectsTo: ["toi1"], isOptional: false, priority: 10, stretchAxis: "both", shrinkPriority: 1 },
      { id: "toi1", name: "PREMIUM ATTACHED BATH", type: "attached_toilet", minWidthFt: 6, minLengthFt: 8, minAreaSqFt: 48, preferredVastu: ["W"], connectsTo: ["bed1"], isOptional: false, priority: 9, stretchAxis: "none", shrinkPriority: 6 },
    ],
  },

  {
    id: "TOPOLOGY-RENTAL-OWNER-DUPLEX",
    name: "RENTAL UNITS + OWNER DUPLEX HYBRID",
    description: "Ground Floor full/half parking with 1BHK rental unit & dedicated external stair to Owner Duplex above.",
    category: "Rental + Owner",
    minPlotWidth: 28,
    maxPlotWidth: 45,
    minPlotLength: 38,
    maxPlotLength: 60,
    supportedFacings: ["East", "West", "North", "South"],
    supportedFloors: [3, 4, 5],
    verticalCore: {
      lift: { xRatio: 0.6, yRatio: 0.4, wFt: 5.0, hFt: 5.0 },
      stair: { xRatio: 0.8, yRatio: 0.5, wFt: 7.5, hFt: 15.0, type: "Dog-Legged" },
      shaft: { xRatio: 0.9, yRatio: 0.9, wFt: 3.0, hFt: 3.0 },
    },
    vastuBaseScore: 91,
    spaceBaseScore: 97,
    ventilationBaseScore: 90,
    roomNodes: [
      { id: "park", name: "STILT VEHICLE PARKING", type: "parking", minWidthFt: 15, minLengthFt: 15, minAreaSqFt: 225, preferredVastu: ["NW", "SE"], connectsTo: ["stair"], isOptional: false, priority: 10, stretchAxis: "both", shrinkPriority: 1 },
      { id: "rent_liv", name: "RENTAL UNIT LIVING", type: "living", minWidthFt: 10, minLengthFt: 11, minAreaSqFt: 110, preferredVastu: ["NE"], connectsTo: ["rent_kit"], isOptional: false, priority: 8, stretchAxis: "both", shrinkPriority: 2 },
      { id: "rent_kit", name: "RENTAL KITCHENETTE", type: "kitchen", minWidthFt: 6, minLengthFt: 8, minAreaSqFt: 48, preferredVastu: ["SE"], connectsTo: ["rent_liv"], isOptional: false, priority: 8, stretchAxis: "none", shrinkPriority: 3 },
      { id: "rent_bed", name: "RENTAL BEDROOM", type: "bedroom", minWidthFt: 10, minLengthFt: 10, minAreaSqFt: 100, preferredVastu: ["NW"], connectsTo: ["rent_toi"], isOptional: false, priority: 8, stretchAxis: "both", shrinkPriority: 2 },
      { id: "rent_toi", name: "RENTAL TOILET", type: "common_toilet", minWidthFt: 4, minLengthFt: 7, minAreaSqFt: 28, preferredVastu: ["W"], connectsTo: ["rent_bed"], isOptional: false, priority: 7, stretchAxis: "none", shrinkPriority: 4 },
    ],
  },

  {
    id: "TOPOLOGY-4060-PREMIUM-VILLA",
    name: "40x60 PREMIUM ARCHITECTURAL VILLA",
    description: "Spacious 40x60 villa with dual living halls, home theater provision & 3-car parking stilt.",
    category: "40x60 Villa",
    minPlotWidth: 36,
    maxPlotWidth: 45,
    minPlotLength: 52,
    maxPlotLength: 68,
    supportedFacings: ["East", "North", "South", "West"],
    supportedFloors: [2, 3, 4],
    verticalCore: {
      lift: { xRatio: 0.55, yRatio: 0.45, wFt: 6.0, hFt: 6.0 },
      stair: { xRatio: 0.7, yRatio: 0.5, wFt: 8.5, hFt: 17.0, type: "Open-Well" },
      shaft: { xRatio: 0.85, yRatio: 0.85, wFt: 4.0, hFt: 4.0 },
    },
    vastuBaseScore: 99,
    spaceBaseScore: 96,
    ventilationBaseScore: 98,
    roomNodes: [
      { id: "liv", name: "ROYAL FOYER & LIVING", type: "living", minWidthFt: 16, minLengthFt: 16, minAreaSqFt: 256, preferredVastu: ["NE"], connectsTo: ["din"], isOptional: false, priority: 10, stretchAxis: "both", shrinkPriority: 1 },
      { id: "din", name: "FORMAL DINING (10 SEATER)", type: "dining", minWidthFt: 14, minLengthFt: 13, minAreaSqFt: 182, preferredVastu: ["E", "CENTER"], connectsTo: ["liv", "kit"], isOptional: false, priority: 9, stretchAxis: "both", shrinkPriority: 2 },
      { id: "kit", name: "ISLAND KITCHEN & PANTRY", type: "kitchen", minWidthFt: 13, minLengthFt: 12, minAreaSqFt: 156, preferredVastu: ["SE"], connectsTo: ["din", "util", "store"], isOptional: false, priority: 10, stretchAxis: "both", shrinkPriority: 3 },
      { id: "util", name: "HEAVY DUTY UTILITY", type: "utility", minWidthFt: 7, minLengthFt: 9, minAreaSqFt: 63, preferredVastu: ["SE"], connectsTo: ["kit"], isOptional: false, priority: 8, stretchAxis: "none", shrinkPriority: 4 },
      { id: "store", name: "WALK-IN PANTRY / STORE", type: "store", minWidthFt: 5, minLengthFt: 7, minAreaSqFt: 35, preferredVastu: ["S"], connectsTo: ["kit"], isOptional: false, priority: 7, stretchAxis: "none", shrinkPriority: 5 },
      { id: "bed1", name: "PRESIDENTIAL MASTER SUITE", type: "master_bedroom", minWidthFt: 15, minLengthFt: 16, minAreaSqFt: 240, preferredVastu: ["SW"], connectsTo: ["toi1"], isOptional: false, priority: 10, stretchAxis: "both", shrinkPriority: 1 },
      { id: "toi1", name: "LUXURY MASTER BATH & TUB", type: "attached_toilet", minWidthFt: 8, minLengthFt: 10, minAreaSqFt: 80, preferredVastu: ["W"], connectsTo: ["bed1"], isOptional: false, priority: 9, stretchAxis: "none", shrinkPriority: 6 },
    ],
  },

  {
    id: "TOPOLOGY-5080-LUXURY-ESTATE",
    name: "50x80 / 60x80 LARGE ESTATE RESIDENCE",
    description: "Palatial multi-generational villa layout with central brahmastan courtyard & perimeter lawn garden.",
    category: "Large Villa",
    minPlotWidth: 46,
    maxPlotWidth: 70,
    minPlotLength: 70,
    maxPlotLength: 100,
    supportedFacings: ["East", "North", "South", "West"],
    supportedFloors: [2, 3, 4],
    verticalCore: {
      lift: { xRatio: 0.5, yRatio: 0.45, wFt: 6.5, hFt: 6.5 },
      stair: { xRatio: 0.65, yRatio: 0.5, wFt: 9.0, hFt: 18.0, type: "Open-Well" },
      shaft: { xRatio: 0.85, yRatio: 0.85, wFt: 4.5, hFt: 4.5 },
    },
    vastuBaseScore: 100,
    spaceBaseScore: 99,
    ventilationBaseScore: 100,
    roomNodes: [
      { id: "liv", name: "GRAND PALATIAL LIVING", type: "living", minWidthFt: 18, minLengthFt: 20, minAreaSqFt: 360, preferredVastu: ["NE"], connectsTo: ["din"], isOptional: false, priority: 10, stretchAxis: "both", shrinkPriority: 1 },
      { id: "din", name: "BANQUET DINING HALL", type: "dining", minWidthFt: 16, minLengthFt: 15, minAreaSqFt: 240, preferredVastu: ["E", "CENTER"], connectsTo: ["liv", "kit"], isOptional: false, priority: 9, stretchAxis: "both", shrinkPriority: 2 },
      { id: "kit", name: "CHEF'S KITCHEN & PREP KITCHEN", type: "kitchen", minWidthFt: 15, minLengthFt: 14, minAreaSqFt: 210, preferredVastu: ["SE"], connectsTo: ["din", "util"], isOptional: false, priority: 10, stretchAxis: "both", shrinkPriority: 3 },
      { id: "bed1", name: "MASTER SUITE WITH DRESSING", type: "master_bedroom", minWidthFt: 16, minLengthFt: 18, minAreaSqFt: 288, preferredVastu: ["SW"], connectsTo: ["toi1"], isOptional: false, priority: 10, stretchAxis: "both", shrinkPriority: 1 },
      { id: "toi1", name: "SPA ATTACHED BATH", type: "attached_toilet", minWidthFt: 9, minLengthFt: 12, minAreaSqFt: 108, preferredVastu: ["W"], connectsTo: ["bed1"], isOptional: false, priority: 9, stretchAxis: "none", shrinkPriority: 4 },
    ],
  },
];
