// BUILDMITRA DRG ENGINE — PHASE 1 TEST CASES & BENCHMARK PRESETS
// ISOLATED FROM PRODUCTION DEFAULTS (utils/drg/drgPhase1TestCases.ts)

import { ProjectRequirementModel } from "./projectRequirementModel";

// TEST CASE A: 30x40 South Facing G+2 Duplex (Residential)
export const TEST_CASE_A_MODEL: ProjectRequirementModel = {
  version: "1.0.0",
  status: "draft",
  isConfirmed: false,
  updatedAt: "2026-08-08T12:00:00.000Z",
  project: {
    projectName: "Reddy Residence (Case A)",
    clientName: "Srikanth Reddy",
    projectLocation: "Indiranagar",
    city: "Bengaluru",
    state: "Karnataka",
    pinCode: "560038",
    projectType: "Duplex",
    constructionType: "New Construction",
    notes: "30x40 South facing plot with G+2 Duplex configuration and ground full parking.",
  },
  plot: {
    plotWidth: 30,
    plotLength: 40,
    plotAreaSqFt: 1200,
    plotUnit: "Feet",
    siteFacing: "South",
    roadSide: "South",
    roadWidthFt: 30,
    plotShape: "Rectangular",
    isCornerPlot: false,
  },
  siteSoil: {
    isSoilTestAvailable: true,
    sbcKpa: 200,
    sbcUnit: "kN/m²",
    soilType: "Medium Clay",
    groundwaterInfo: "Below 12 ft",
    siteSlope: "Flat",
    hasExistingStructures: false,
  },
  setbacks: {
    mode: "User Provided",
    requestedSetback: { front: 5, rear: 3, left: 3, right: 3 },
    finalAcceptedSetback: { front: 5, rear: 3, left: 3, right: 3 },
  },
  building: {
    numberOfFloors: 3,
    floorLabels: ["Ground Floor", "First Floor", "Second Floor"],
    hasBasement: false,
    hasStilt: true,
    terraceUse: "Open Terrace & Solar",
  },
  floors: [
    {
      floorIndex: 0,
      floorLabel: "Ground Floor",
      floorType: "Full Parking",
      parking: {
        parkingMode: "Full Parking",
        carsCount: 2,
        twoWheelersCount: 4,
        evChargingRequired: true,
        visitorParkingCount: 1,
      },
      rooms: {
        livingRoomCount: 0,
        diningCount: 0,
        kitchenCount: 0,
        utilityCount: 0,
        masterBedrooms: 0,
        otherBedrooms: 0,
        guestBedrooms: 0,
        childrenBedrooms: 0,
        attachedToilets: 0,
        commonToilets: 1,
        poojaRoom: false,
        studyRoom: false,
        homeOffice: false,
        familyLounge: false,
        storeRoom: false,
        laundryRoom: false,
        walkInWardrobe: false,
        balconiesCount: 0,
        sitOutCount: 0,
        hasTerrace: false,
        servantRoom: false,
        servantToilet: false,
        gym: false,
        homeTheatre: false,
        partyHall: false,
        customRooms: [],
      },
    },
    {
      floorIndex: 1,
      floorLabel: "First Floor",
      floorType: "Duplex Lower Living",
      parking: {
        parkingMode: "No Parking",
        carsCount: 0,
        twoWheelersCount: 0,
        evChargingRequired: false,
        visitorParkingCount: 0,
      },
      rooms: {
        livingRoomCount: 1,
        diningCount: 1,
        kitchenCount: 1,
        utilityCount: 1,
        masterBedrooms: 1,
        otherBedrooms: 1,
        guestBedrooms: 0,
        childrenBedrooms: 0,
        attachedToilets: 2,
        commonToilets: 1,
        poojaRoom: true,
        studyRoom: false,
        homeOffice: false,
        familyLounge: true,
        storeRoom: true,
        laundryRoom: false,
        walkInWardrobe: false,
        balconiesCount: 1,
        sitOutCount: 1,
        hasTerrace: false,
        servantRoom: false,
        servantToilet: false,
        gym: false,
        homeTheatre: false,
        partyHall: false,
        customRooms: [],
      },
    },
    {
      floorIndex: 2,
      floorLabel: "Second Floor",
      floorType: "Duplex Upper Bedrooms",
      parking: {
        parkingMode: "No Parking",
        carsCount: 0,
        twoWheelersCount: 0,
        evChargingRequired: false,
        visitorParkingCount: 0,
      },
      rooms: {
        livingRoomCount: 0,
        diningCount: 0,
        kitchenCount: 0,
        utilityCount: 0,
        masterBedrooms: 1,
        otherBedrooms: 2,
        guestBedrooms: 0,
        childrenBedrooms: 1,
        attachedToilets: 3,
        commonToilets: 0,
        poojaRoom: false,
        studyRoom: true,
        homeOffice: false,
        familyLounge: true,
        storeRoom: false,
        laundryRoom: true,
        walkInWardrobe: true,
        balconiesCount: 2,
        sitOutCount: 0,
        hasTerrace: true,
        servantRoom: false,
        servantToilet: false,
        gym: false,
        homeTheatre: false,
        partyHall: false,
        customRooms: [],
      },
    },
  ],
  duplexTriplex: {
    isDuplex: true,
    duplexFloors: [1, 2],
    internalStaircaseRequired: true,
    isTriplex: false,
  },
  verticalCirculation: {
    staircase: {
      required: true,
      typePreference: "Dog-legged",
      locationPref: "Vastu Recommended",
    },
    lift: {
      required: true,
      passengerCapacity: "4 Person",
      locationPref: "Near Main Entrance",
    },
  },
  waterServices: {
    ugWaterSumpRequired: true,
    ugWaterSumpCapacityLiters: 8000,
    overheadTankRequired: true,
    overheadTankCapacityLiters: 4000,
    rainwaterHarvestingRequired: true,
    borewellRequired: true,
    solarRequirement: true,
  },
  vastu: {
    level: "Strict",
    mainDoorDirection: "East",
    kitchenDirection: "SE",
    masterBedDirection: "SW",
  },
  structuralInputs: {
    structuralSystemPreference: "RCC Frame",
  },
  constructionPreferences: {
    wallType: "AAC Block",
    constructionQuality: "Premium",
  },
  userPriorities: {
    maxBuiltUpArea: 4,
    moreOpenSpace: 3,
    moreParking: 5,
    vastuCompliance: 5,
    naturalLightVentilation: 4,
  },
};

// TEST CASE B: 40x60 East Facing Multi-Unit (UNVERIFIED / MISSING SBC TRIGGER)
export const TEST_CASE_B_MODEL: ProjectRequirementModel = {
  version: "1.0.0",
  status: "draft",
  isConfirmed: false,
  updatedAt: "2026-08-08T12:00:00.000Z",
  project: {
    projectName: "Sharma Multi-Unit (Case B - Blank SBC Warning)",
    clientName: "Ramesh Sharma",
    projectLocation: "HSR Layout",
    city: "Bengaluru",
    state: "Karnataka",
    pinCode: "560102",
    projectType: "Apartment",
    constructionType: "New Construction",
    notes: "40x60 East facing multi-unit building with UNVERIFIED soil SBC to test alert banner.",
  },
  plot: {
    plotWidth: 40,
    plotLength: 60,
    plotAreaSqFt: 2400,
    plotUnit: "Feet",
    siteFacing: "East",
    roadSide: "East",
    roadWidthFt: 40,
    plotShape: "Rectangular",
    isCornerPlot: false,
  },
  siteSoil: {
    isSoilTestAvailable: false, // TRIPPED UNVERIFIED SBC WARNING
    sbcKpa: 0,
    sbcUnit: "kN/m²",
    soilType: "Awaiting Soil Test",
    groundwaterInfo: "Unknown",
    siteSlope: "Flat",
    hasExistingStructures: false,
  },
  setbacks: {
    mode: "Auto Recommend",
    requestedSetback: { front: 6, rear: 4, left: 4, right: 4 },
    finalAcceptedSetback: { front: 6, rear: 4, left: 4, right: 4 },
  },
  building: {
    numberOfFloors: 4,
    floorLabels: ["Ground Floor", "First Floor", "Second Floor", "Third Floor"],
    hasBasement: false,
    hasStilt: true,
    terraceUse: "Common Terrace",
  },
  floors: [
    {
      floorIndex: 0,
      floorLabel: "Ground Floor",
      floorType: "Stilt Parking & 1BHK",
      parking: {
        parkingMode: "Half Parking",
        carsCount: 3,
        twoWheelersCount: 6,
        evChargingRequired: true,
        visitorParkingCount: 2,
      },
      rooms: {
        livingRoomCount: 1,
        diningCount: 1,
        kitchenCount: 1,
        utilityCount: 1,
        masterBedrooms: 1,
        otherBedrooms: 0,
        guestBedrooms: 0,
        childrenBedrooms: 0,
        attachedToilets: 1,
        commonToilets: 1,
        poojaRoom: false,
        studyRoom: false,
        homeOffice: false,
        familyLounge: false,
        storeRoom: false,
        laundryRoom: false,
        walkInWardrobe: false,
        balconiesCount: 0,
        sitOutCount: 0,
        hasTerrace: false,
        servantRoom: false,
        servantToilet: false,
        gym: false,
        homeTheatre: false,
        partyHall: false,
        customRooms: [],
      },
    },
    {
      floorIndex: 1,
      floorLabel: "First Floor",
      floorType: "3BHK Owner Flat",
      parking: {
        parkingMode: "No Parking",
        carsCount: 0,
        twoWheelersCount: 0,
        evChargingRequired: false,
        visitorParkingCount: 0,
      },
      rooms: {
        livingRoomCount: 1,
        diningCount: 1,
        kitchenCount: 1,
        utilityCount: 1,
        masterBedrooms: 1,
        otherBedrooms: 2,
        guestBedrooms: 0,
        childrenBedrooms: 0,
        attachedToilets: 2,
        commonToilets: 1,
        poojaRoom: true,
        studyRoom: true,
        homeOffice: false,
        familyLounge: true,
        storeRoom: true,
        laundryRoom: false,
        walkInWardrobe: false,
        balconiesCount: 2,
        sitOutCount: 1,
        hasTerrace: false,
        servantRoom: false,
        servantToilet: false,
        gym: false,
        homeTheatre: false,
        partyHall: false,
        customRooms: [],
      },
    },
    {
      floorIndex: 2,
      floorLabel: "Second Floor",
      floorType: "2x 2BHK Rental Flats",
      parking: {
        parkingMode: "No Parking",
        carsCount: 0,
        twoWheelersCount: 0,
        evChargingRequired: false,
        visitorParkingCount: 0,
      },
      rooms: {
        livingRoomCount: 2,
        diningCount: 2,
        kitchenCount: 2,
        utilityCount: 2,
        masterBedrooms: 2,
        otherBedrooms: 2,
        guestBedrooms: 0,
        childrenBedrooms: 0,
        attachedToilets: 2,
        commonToilets: 2,
        poojaRoom: false,
        studyRoom: false,
        homeOffice: false,
        familyLounge: false,
        storeRoom: false,
        laundryRoom: false,
        walkInWardrobe: false,
        balconiesCount: 2,
        sitOutCount: 0,
        hasTerrace: false,
        servantRoom: false,
        servantToilet: false,
        gym: false,
        homeTheatre: false,
        partyHall: false,
        customRooms: [],
      },
    },
    {
      floorIndex: 3,
      floorLabel: "Third Floor",
      floorType: "2x 2BHK Rental Flats",
      parking: {
        parkingMode: "No Parking",
        carsCount: 0,
        twoWheelersCount: 0,
        evChargingRequired: false,
        visitorParkingCount: 0,
      },
      rooms: {
        livingRoomCount: 2,
        diningCount: 2,
        kitchenCount: 2,
        utilityCount: 2,
        masterBedrooms: 2,
        otherBedrooms: 2,
        guestBedrooms: 0,
        childrenBedrooms: 0,
        attachedToilets: 2,
        commonToilets: 2,
        poojaRoom: false,
        studyRoom: false,
        homeOffice: false,
        familyLounge: false,
        storeRoom: false,
        laundryRoom: false,
        walkInWardrobe: false,
        balconiesCount: 2,
        sitOutCount: 0,
        hasTerrace: true,
        servantRoom: false,
        servantToilet: false,
        gym: false,
        homeTheatre: false,
        partyHall: false,
        customRooms: [],
      },
    },
  ],
  duplexTriplex: {
    isDuplex: false,
    duplexFloors: [],
    internalStaircaseRequired: false,
    isTriplex: false,
  },
  verticalCirculation: {
    staircase: {
      required: true,
      typePreference: "Dog-legged",
      locationPref: "Vastu Recommended",
    },
    lift: {
      required: true,
      passengerCapacity: "6 Person",
      locationPref: "Central Core",
    },
  },
  waterServices: {
    ugWaterSumpRequired: true,
    ugWaterSumpCapacityLiters: 15000,
    overheadTankRequired: true,
    overheadTankCapacityLiters: 8000,
    rainwaterHarvestingRequired: true,
    borewellRequired: true,
    solarRequirement: true,
  },
  vastu: {
    level: "Preferred",
    mainDoorDirection: "East",
    kitchenDirection: "SE",
    masterBedDirection: "SW",
  },
  structuralInputs: {
    structuralSystemPreference: "RCC Frame",
  },
  constructionPreferences: {
    wallType: "Solid Block",
    constructionQuality: "Standard",
  },
  userPriorities: {
    maxBuiltUpArea: 5,
    moreOpenSpace: 2,
    moreParking: 4,
    vastuCompliance: 4,
    naturalLightVentilation: 4,
  },
};

// TEST CASE C: 60x80 North Facing Luxury Villa G+3
export const TEST_CASE_C_MODEL: ProjectRequirementModel = {
  version: "1.0.0",
  status: "draft",
  isConfirmed: false,
  updatedAt: "2026-08-08T12:00:00.000Z",
  project: {
    projectName: "Verma Luxury Villa (Case C)",
    clientName: "Anil Verma",
    projectLocation: "Sadashivanagar",
    city: "Bengaluru",
    state: "Karnataka",
    pinCode: "560080",
    projectType: "Villa",
    constructionType: "New Construction",
    notes: "60x80 North facing large plot, G+3 Luxury Triplex Villa.",
  },
  plot: {
    plotWidth: 60,
    plotLength: 80,
    plotAreaSqFt: 4800,
    plotUnit: "Feet",
    siteFacing: "North",
    roadSide: "North",
    roadWidthFt: 60,
    plotShape: "Rectangular",
    isCornerPlot: true,
    secondRoadSide: "East",
    secondRoadWidthFt: 40,
  },
  siteSoil: {
    isSoilTestAvailable: true,
    sbcKpa: 280,
    sbcUnit: "kN/m²",
    soilType: "Hard Gravel Clay",
    groundwaterInfo: "Below 20 ft",
    siteSlope: "Flat",
    hasExistingStructures: false,
  },
  setbacks: {
    mode: "User Provided",
    requestedSetback: { front: 10, rear: 6, left: 6, right: 6 },
    finalAcceptedSetback: { front: 10, rear: 6, left: 6, right: 6 },
  },
  building: {
    numberOfFloors: 4,
    floorLabels: ["Ground Floor", "First Floor", "Second Floor", "Third Floor"],
    hasBasement: true,
    hasStilt: false,
    terraceUse: "Roof Garden & Pool",
  },
  floors: [
    {
      floorIndex: 0,
      floorLabel: "Ground Floor",
      floorType: "Formal Living & Parking",
      parking: {
        parkingMode: "Full Parking",
        carsCount: 4,
        twoWheelersCount: 6,
        evChargingRequired: true,
        visitorParkingCount: 3,
      },
      rooms: {
        livingRoomCount: 2,
        diningCount: 1,
        kitchenCount: 1,
        utilityCount: 1,
        masterBedrooms: 0,
        otherBedrooms: 1,
        guestBedrooms: 1,
        childrenBedrooms: 0,
        attachedToilets: 2,
        commonToilets: 1,
        poojaRoom: true,
        studyRoom: true,
        homeOffice: true,
        familyLounge: false,
        storeRoom: true,
        laundryRoom: false,
        walkInWardrobe: false,
        balconiesCount: 1,
        sitOutCount: 2,
        hasTerrace: false,
        servantRoom: true,
        servantToilet: true,
        gym: false,
        homeTheatre: false,
        partyHall: false,
        customRooms: [],
      },
    },
    {
      floorIndex: 1,
      floorLabel: "First Floor",
      floorType: "Triplex Family Floor",
      parking: {
        parkingMode: "No Parking",
        carsCount: 0,
        twoWheelersCount: 0,
        evChargingRequired: false,
        visitorParkingCount: 0,
      },
      rooms: {
        livingRoomCount: 1,
        diningCount: 1,
        kitchenCount: 1,
        utilityCount: 1,
        masterBedrooms: 2,
        otherBedrooms: 1,
        guestBedrooms: 0,
        childrenBedrooms: 1,
        attachedToilets: 4,
        commonToilets: 0,
        poojaRoom: false,
        studyRoom: true,
        homeOffice: false,
        familyLounge: true,
        storeRoom: false,
        laundryRoom: true,
        walkInWardrobe: true,
        balconiesCount: 3,
        sitOutCount: 1,
        hasTerrace: false,
        servantRoom: false,
        servantToilet: false,
        gym: false,
        homeTheatre: false,
        partyHall: false,
        customRooms: [],
      },
    },
    {
      floorIndex: 2,
      floorLabel: "Second Floor",
      floorType: "Triplex Entertainment & Gym",
      parking: {
        parkingMode: "No Parking",
        carsCount: 0,
        twoWheelersCount: 0,
        evChargingRequired: false,
        visitorParkingCount: 0,
      },
      rooms: {
        livingRoomCount: 1,
        diningCount: 0,
        kitchenCount: 0,
        utilityCount: 0,
        masterBedrooms: 1,
        otherBedrooms: 1,
        guestBedrooms: 0,
        childrenBedrooms: 0,
        attachedToilets: 2,
        commonToilets: 1,
        poojaRoom: false,
        studyRoom: false,
        homeOffice: false,
        familyLounge: true,
        storeRoom: false,
        laundryRoom: false,
        walkInWardrobe: true,
        balconiesCount: 2,
        sitOutCount: 0,
        hasTerrace: true,
        servantRoom: false,
        servantToilet: false,
        gym: true,
        homeTheatre: true,
        partyHall: false,
        customRooms: [],
      },
    },
    {
      floorIndex: 3,
      floorLabel: "Third Floor",
      floorType: "Sky Lounge & Terrace Pool",
      parking: {
        parkingMode: "No Parking",
        carsCount: 0,
        twoWheelersCount: 0,
        evChargingRequired: false,
        visitorParkingCount: 0,
      },
      rooms: {
        livingRoomCount: 1,
        diningCount: 0,
        kitchenCount: 1,
        utilityCount: 0,
        masterBedrooms: 0,
        otherBedrooms: 0,
        guestBedrooms: 0,
        childrenBedrooms: 0,
        attachedToilets: 1,
        commonToilets: 1,
        poojaRoom: false,
        studyRoom: false,
        homeOffice: false,
        familyLounge: true,
        storeRoom: false,
        laundryRoom: false,
        walkInWardrobe: false,
        balconiesCount: 2,
        sitOutCount: 2,
        hasTerrace: true,
        servantRoom: false,
        servantToilet: false,
        gym: false,
        homeTheatre: false,
        partyHall: true,
        customRooms: [],
      },
    },
  ],
  duplexTriplex: {
    isDuplex: false,
    duplexFloors: [],
    internalStaircaseRequired: true,
    isTriplex: true,
  },
  verticalCirculation: {
    staircase: {
      required: true,
      typePreference: "Open well",
      locationPref: "Vastu Recommended",
    },
    lift: {
      required: true,
      passengerCapacity: "8 Person",
      locationPref: "Central Foyer",
    },
  },
  waterServices: {
    ugWaterSumpRequired: true,
    ugWaterSumpCapacityLiters: 25000,
    overheadTankRequired: true,
    overheadTankCapacityLiters: 12000,
    rainwaterHarvestingRequired: true,
    borewellRequired: true,
    solarRequirement: true,
  },
  vastu: {
    level: "Strict",
    mainDoorDirection: "North",
    kitchenDirection: "SE",
    masterBedDirection: "SW",
  },
  structuralInputs: {
    structuralSystemPreference: "RCC Frame",
  },
  constructionPreferences: {
    wallType: "AAC Block",
    constructionQuality: "Luxury",
  },
  userPriorities: {
    maxBuiltUpArea: 5,
    moreOpenSpace: 5,
    moreParking: 5,
    vastuCompliance: 5,
    naturalLightVentilation: 5,
  },
};
