import React, { useState } from 'react';

const InteriorBOQ = () => {
  const [items, setItems] = useState([
    { id: 1, name: 'Wardrobe (per bedroom)', type: 'sqft', l: 6, w: 2, h: 7, qty: 84, unit: 'sqft', rate: 800 },
    { id: 2, name: 'Modular Kitchen', type: 'sqft', l: 10, w: 2, h: 2.5, qty: 50, unit: 'sqft', rate: 4500 },
    { id: 3, name: 'TV Unit', type: 'sqft', l: 8, w: 1.5, h: 2, qty: 24, unit: 'sqft', rate: 1200 },
    { id: 4, name: 'Pooja Room Unit', type: 'sqft', l: 4, w: 2, h: 3, qty: 24, unit: 'sqft', rate: 1500 },
    { id: 5, name: 'Shoe Rack', type: 'sqft', l: 3, w: 1, h: 3, qty: 9, unit: 'sqft', rate: 600 },
    { id: 6, name: 'False Ceiling', type: 'sqft', l: 20, w: 15, qty: 300, unit: 'sqft', rate: 180 },
    { id: 7, name: 'LED Strip', type: 'lft', l: 70, qty: 70, unit: 'lft', rate: 120 },
    { id: 8, name: 'LED Spotlight', type: 'nos', qty: 10, unit: 'nos', rate: 450 },
    { id: 9, name: 'Chandelier', type: 'nos', qty: 1, unit: 'nos', rate: 8000 },
    { id: 10, name: 'Plywood (19mm)', type: 'sqft', qty: 25, unit: 'sqft', rate: 85 },
    { id: 11, name: 'Plywood (12mm)', type: 'sqft', qty: 15, unit: 'sqft', rate: 65 },
    { id: 12, name: 'Laminates (inner)', type: 'sqft', qty: 25, unit: 'sqft', rate: 35 },
    { id: 13, name: 'Laminates (outer)', type: 'sqft', qty: 25, unit: 'sqft', rate: 65 },
    { id: 14, name: 'Hinges (SS 4")', type: 'nos', qty: 40, unit: 'nos', rate: 45 },
    { id: 15, name: 'Kitchen Accessories set', type: 'nos', qty: 1, unit: 'set', rate: 3500 },
    { id: 16, name: 'Fevicol SH', type: 'nos', qty: 5, unit: 'nos', rate: 180 },
    { id: 17, name: 'Nails (assorted)', type: 'kg', qty: 2, unit: 'kg', rate: 120 },
    { id: 18, name: 'Labour', type: 'lump', qty: 1, unit: 'ls', rate: 25000 },
  ]);

  const [newItem, setNewItem] = useState({ name: '', type: 'sqft', l: 0, w: 0, h: 0, qty: 1, unit: 'sqft', rate: 0 });

  const calcQty = (item) => {
    if (item.type === 'sqft') return (item.l || 0) * (item.w || 0) * (item.h || 1);
    if (item.type === 'lft') return item.l || 0;
    return item.qty || 0;
  };

  const updateItem = (idx, field, val) => {
    const updated = [...items];
    let nv = (field === 'rate' || field === 'qty' || field === 'l' || field === 'w' || field === 'h') ? parseFloat(val) || 0 : val;
    updated[idx][field] = nv;
    if (['l','w','h','type'].includes(field)) updated[idx].qty = calcQty(updated[idx]);
    setItems(updated);
  };

  const addCustomItem = () => {
    if (!newItem.name) return;
    const qty = newItem.type === 'sqft' ? (newItem.l * newItem.w * (newItem.h||1)) : (newItem.type === 'lft' ? newItem.l : newItem.qty);
    setItems([...items, { id: Date.now(), name: newItem.name, type: newItem.type, l: newItem.l, w: newItem.w, h: newItem.h, qty: qty||1, unit: newItem.unit, rate: newItem.rate }]);
    setNewItem({ name: '', type: 'sqft', l: 0, w: 0, h: 0, qty: 1, unit: 'sqft', rate: 0 });
  };

  const deleteItem = (idx) => setItems(items.filter((_,i) => i !== idx));

  const total = items.reduce((s,i) => s + (i.qty * i.rate), 0);

  const exportCSV = () => {
    const rows = [['Item','Type','Dimensions','Qty','Unit','Rate','Amount']];
    items.forEach(i => {
      let dims = i.type === 'sqft' ? `${i.l}x${i.w}x${i.h}` : (i.type === 'lft' ? `${i.l} ft` : '-');
      rows.push([i.name, i.type, dims, i.qty, i.unit, i.rate, (i.qty*i.rate).toFixed(2)]);
    });
    const csv = rows.map(r => r.join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'interior_boq.csv';
    a.click();
    URL.revokeObjectURL(url);
  };

  const shareWhatsApp = () => {
    const msg = `🏠 BUILD MITRA - INTERIOR BOQ%0ATotal: ₹${total.toLocaleString(undefined,{minimumFractionDigits:2})}%0AGenerated by BuildMitra`;
    window.open(`https://wa.me/?text=${msg}`, '_blank');
  };

  return (
    <div className="card p-6">
      <h2 className="text-2xl font-bold mb-4">🏠 Interior BOQ (Editable Table – No Paint)</h2>
      <div className="flex gap-3 mb-6">
        <button onClick={exportCSV} className="bg-blue-600 text-white px-5 py-2 rounded-xl">📎 Export CSV</button>
        <button onClick={shareWhatsApp} className="bg-green-500 text-white px-5 py-2 rounded-xl">📱 WhatsApp</button>
        <button onClick={()=>window.print()} className="bg-purple-600 text-white px-5 py-2 rounded-xl">🖨️ Print</button>
      </div>
      <div className="overflow-x-auto">
        <table className="w-full text-sm border rounded-lg">
          <thead className="bg-gray-100">
            <tr>
              <th className="p-2 border">Item</th>
              <th className="p-2 border">Type</th>
              <th className="p-2 border">Dimensions (LxWxH ft)</th>
              <th className="p-2 border">Qty</th>
              <th className="p-2 border">Unit</th>
              <th className="p-2 border">Rate (₹)</th>
              <th className="p-2 border">Amount (₹)</th>
              <th className="p-2 border">Actions</th>
            </tr>
          </thead>
          <tbody>
            {items.map((i, idx) => (
              <tr key={i.id} className="even:bg-gray-50">
                <td className="p-2 border"><input type="text" value={i.name} onChange={e=>updateItem(idx,'name',e.target.value)} className="input-field w-40" /></td>
                <td className="p-2 border">
                  <select value={i.type} onChange={e=>updateItem(idx,'type',e.target.value)} className="input-field w-24">
                    <option value="sqft">sqft</option><option value="lft">lft</option><option value="nos">nos</option>
                  </select>
                </td>
                <td className="p-2 border">
                  {i.type === 'sqft' && <><input type="number" value={i.l} onChange={e=>updateItem(idx,'l',e.target.value)} className="input-field w-20" />x<input type="number" value={i.w} onChange={e=>updateItem(idx,'w',e.target.value)} className="input-field w-20" />x<input type="number" value={i.h||1} onChange={e=>updateItem(idx,'h',e.target.value)} className="input-field w-20" /></>}
                  {i.type === 'lft' && <input type="number" value={i.l} onChange={e=>updateItem(idx,'l',e.target.value)} className="input-field w-24" />}
                  {i.type === 'nos' && <span>-</span>}
                </td>
                <td className="p-2 border">{i.qty.toFixed(2)}</td>
                <td className="p-2 border"><input type="text" value={i.unit} onChange={e=>updateItem(idx,'unit',e.target.value)} className="input-field w-20" /></td>
                <td className="p-2 border"><input type="number" value={i.rate} onChange={e=>updateItem(idx,'rate',e.target.value)} className="input-field w-28" /></td>
                <td className="p-2 border">₹{(i.qty*i.rate).toLocaleString(undefined,{minimumFractionDigits:2})}</td>
                <td className="p-2 border"><button onClick={()=>deleteItem(idx)} className="text-red-600">X</button></td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <div className="flex flex-wrap gap-2 mt-4 mb-4 items-end">
        <input type="text" placeholder="Item name" value={newItem.name} onChange={e=>setNewItem({...newItem, name:e.target.value})} className="input-field w-40" />
        <select value={newItem.type} onChange={e=>setNewItem({...newItem, type:e.target.value})} className="input-field w-24">
          <option value="sqft">sqft</option><option value="lft">lft</option><option value="nos">nos</option>
        </select>
        {newItem.type === 'sqft' && <><input type="number" placeholder="L" value={newItem.l} onChange={e=>setNewItem({...newItem, l:parseFloat(e.target.value)||0})} className="input-field w-20" />
          <input type="number" placeholder="W" value={newItem.w} onChange={e=>setNewItem({...newItem, w:parseFloat(e.target.value)||0})} className="input-field w-20" />
          <input type="number" placeholder="H" value={newItem.h} onChange={e=>setNewItem({...newItem, h:parseFloat(e.target.value)||0})} className="input-field w-20" /></>}
        {newItem.type === 'lft' && <input type="number" placeholder="Length" value={newItem.l} onChange={e=>setNewItem({...newItem, l:parseFloat(e.target.value)||0})} className="input-field w-28" />}
        {newItem.type === 'nos' && <input type="number" placeholder="Qty" value={newItem.qty} onChange={e=>setNewItem({...newItem, qty:parseFloat(e.target.value)||0})} className="input-field w-28" />}
        <input type="number" placeholder="Rate" value={newItem.rate} onChange={e=>setNewItem({...newItem, rate:parseFloat(e.target.value)||0})} className="input-field w-28" />
        <button onClick={addCustomItem} className="btn-secondary">+ Add Custom Item</button>
      </div>
      <div className="mt-4 text-right font-bold text-lg">Total: ₹{total.toLocaleString(undefined,{minimumFractionDigits:2})}</div>
    </div>
  );
};

export default InteriorBOQ;