import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const exportToExcel = (data: any[], fileName: string = 'BOQ_Report') => {
  const ws = XLSX.utils.json_to_sheet(data);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'BOQ');
  XLSX.writeFile(wb, `${fileName}.xlsx`);
};

export const exportToPDF = (data: any[], columns: string[], fileName: string = 'BOQ_Report') => {
  const doc = new jsPDF();
  doc.text('Bill of Quantities (BOQ)', 14, 16);
  autoTable(doc, {
    head: [columns],
    body: data.map(row => columns.map(col => row[col])),
    startY: 20,
  });
  doc.save(`${fileName}.pdf`);
};

export const shareWhatsApp = (text: string) => {
  const url = `https://wa.me/?text=${encodeURIComponent(text)}`;
  window.open(url, '_blank');
};

export const generateShareMessage = (totalAmount: number) => {
  return `📋 *BOQ Report* 📋\nTotal Amount: ₹${totalAmount.toFixed(2)}\nGenerated by BuildMitra.`;
};