import React, { useMemo, useState } from "react";
import { useRouter } from "next/router";
import * as XLSX from "xlsx";
import jsPDF from "jspdf";

type SurveyPoint={id:number;name:string;distance:number;bearing:number};
type PlotType={id:number;name:string;width:number;depth:number;allocation:number};
type AmenityKey=typeof AMENITIES[number];
type XY={x:number;y:number};
type Box={x:number;y:number;w:number;h:number};
type DevelopmentStrategy="Maximize Plots"|"Balanced Development"|"Premium Development"|"User Controlled Allocation";
type GeneratedPlot=Box&{number:number;type:string;width:number;depth:number;area:number;roadAccess:boolean;adjusted:boolean;premium:boolean;corner:boolean;odd:boolean;shape?:XY[]};
type AmenityBox=Box&{name:string;color:string};
type BoqRow={category:string;item:string;qty:number;unit:string;rate:number;amount:number};

const AMENITIES=["Park","Children Park","Club House","Swimming Pool","STP","UG Tank","Overhead Tank","Jogging Track","Open Gym","Temple","Commercial Block","Security Cabin","Visitors Parking","Compound Wall","Main Entrance Arch","Transformer Yard","Rain Water Harvesting","Landscape Area"] as const;
const PARK_NAMES=new Set<string>(["Park","Children Park","Landscape Area","Jogging Track","Open Gym"]);
const UTILITY_NAMES=new Set<string>(["STP","UG Tank","Overhead Tank","Transformer Yard","Rain Water Harvesting"]);
const COLORS={road:"#64748b",plot:"#fef3c7",plotStroke:"#92400e",park:"#bbf7d0",amenity:"#bfdbfe",utility:"#ddd6fe",commercial:"#fed7aa"};
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number.isFinite(n)?n:0);
const num=(n:number,d=0)=>new Intl.NumberFormat("en-IN",{maximumFractionDigits:d}).format(Number.isFinite(n)?n:0);
const pointInPolygon=(p:XY,poly:XY[])=>{let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if(((a.y>p.y)!==(b.y>p.y))&&(p.x<(b.x-a.x)*(p.y-a.y)/(b.y-a.y||1e-9)+a.x))inside=!inside;}return inside};
const boxInside=(b:Box,poly:XY[])=>[{x:b.x,y:b.y},{x:b.x+b.w,y:b.y},{x:b.x+b.w,y:b.y+b.h},{x:b.x,y:b.y+b.h},{x:b.x+b.w/2,y:b.y+b.h/2}].every(p=>pointInPolygon(p,poly)||poly.some(v=>Math.abs(v.x-p.x)<.01&&Math.abs(v.y-p.y)<.01));
const overlaps=(a:Box,b:Box)=>a.x<b.x+b.w-.01&&a.x+a.w>b.x+.01&&a.y<b.y+b.h-.01&&a.y+a.h>b.y+.01;
const polygonArea=(poly:XY[])=>Math.abs(poly.reduce((s,p,i)=>{const q=poly[(i+1)%poly.length];return s+p.x*q.y-q.x*p.y},0))/2;
const perimeter=(poly:XY[])=>poly.reduce((s,p,i)=>{const q=poly[(i+1)%poly.length];return s+Math.hypot(q.x-p.x,q.y-p.y)},0);
const horizontalSpan=(poly:XY[],y:number)=>{const hits:number[]=[];for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length];if((a.y<=y&&b.y>y)||(b.y<=y&&a.y>y))hits.push(a.x+(b.x-a.x)*(y-a.y)/(b.y-a.y));}hits.sort((a,b)=>a-b);return hits.length>=2?{min:hits[0],max:hits[hits.length-1]}:null};
const boxPolygonArea=(box:Box,source:XY[])=>{let out=source;const edges=[{inside:(p:XY)=>p.x>=box.x,hit:(a:XY,b:XY)=>({x:box.x,y:a.y+(b.y-a.y)*(box.x-a.x)/(b.x-a.x||1e-9)})},{inside:(p:XY)=>p.x<=box.x+box.w,hit:(a:XY,b:XY)=>({x:box.x+box.w,y:a.y+(b.y-a.y)*(box.x+box.w-a.x)/(b.x-a.x||1e-9)})},{inside:(p:XY)=>p.y>=box.y,hit:(a:XY,b:XY)=>({x:a.x+(b.x-a.x)*(box.y-a.y)/(b.y-a.y||1e-9),y:box.y})},{inside:(p:XY)=>p.y<=box.y+box.h,hit:(a:XY,b:XY)=>({x:a.x+(b.x-a.x)*(box.y+box.h-a.y)/(b.y-a.y||1e-9),y:box.y+box.h})}];for(const edge of edges){const input=out;out=[];for(let i=0;i<input.length;i++){const a=input[i],b=input[(i+1)%input.length],ain=edge.inside(a),bin=edge.inside(b);if(ain&&bin)out.push(b);else if(ain&&!bin)out.push(edge.hit(a,b));else if(!ain&&bin)out.push(edge.hit(a,b),b);}if(!out.length)break;}return out.length>2?polygonArea(out):0};

function surveyPolygon(points:SurveyPoint[]){
  const poly:XY[]=[{x:0,y:0}];
  for(let i=0;i<points.length-1;i++){const p=poly[i],rad=points[i].bearing*Math.PI/180;poly.push({x:p.x+points[i].distance*Math.sin(rad),y:p.y+points[i].distance*Math.cos(rad)});}
  const last=poly[poly.length-1],closing=Math.hypot(last.x,last.y),stated=points[points.length-1]?.distance||0;
  return{poly,closureError:Math.abs(closing-stated),closingDistance:closing};
}

function approximatePolygon(points:SurveyPoint[]){
  const sides=points.map(p=>Math.max(1,p.distance));
  if(sides.length===4){
    const [a,b,c,d]=sides,valid=Math.max(...sides)<sides.reduce((s,n)=>s+n,0)-Math.max(...sides);
    if(valid){
      const diagonal=Math.sqrt(Math.max(1,(a*c+b*d)*(a*d+b*c)/(a*b+c*d||1))),cx=(a*a+diagonal*diagonal-b*b)/(2*a),cy=Math.sqrt(Math.max(1,diagonal*diagonal-cx*cx));
      const ux=cx/diagonal,uy=cy/diagonal,t=(d*d+diagonal*diagonal-c*c)/(2*diagonal),h=Math.sqrt(Math.max(0,d*d-t*t));
      const poly=[{x:0,y:0},{x:a,y:0},{x:cx,y:cy},{x:ux*t-uy*h,y:uy*t+ux*h}];
      return{poly,closureError:0,closingDistance:d};
    }
  }
  const raw:XY[]=[{x:0,y:0}];
  sides.forEach((distance,i)=>{const angle=(-90+i*360/sides.length)*Math.PI/180,p=raw[raw.length-1];raw.push({x:p.x+distance*Math.cos(angle),y:p.y+distance*Math.sin(angle)})});
  const closure=raw[raw.length-1],poly=raw.slice(0,-1).map((p,i)=>({x:p.x-closure.x*i/sides.length,y:p.y-closure.y*i/sides.length}));
  return{poly,closureError:Math.hypot(closure.x,closure.y),closingDistance:sides[sides.length-1]};
}

function makeAmenityBoxes(poly:XY[],selected:AmenityKey[],targetArea:number,bounds:{minX:number;minY:number;maxX:number;maxY:number},forbidden:Box[]=[]):AmenityBox[]{
  if(!selected.length||targetArea<=0)return[];
  const bw=bounds.maxX-bounds.minX,bh=bounds.maxY-bounds.minY,minimum=(name:string)=>name==="Security Cabin"?200:name==="Rain Water Harvesting"?300:name==="Overhead Tank"?400:name==="UG Tank"?600:name==="Transformer Yard"?900:name==="STP"?1200:name==="Swimming Pool"?1800:name==="Club House"?2500:600,minTotal=selected.reduce((s,n)=>s+minimum(n),0),extra=Math.max(0,targetArea-minTotal),boxes:AmenityBox[]=[],cellW=Math.max(18,Math.min(28,bw/28)),cellH=Math.max(16,Math.min(24,bh/30)),cells:Box[]=[];
  for(let y=bounds.minY;y+cellH<=bounds.maxY+.01;y+=cellH)for(let x=bounds.minX;x+cellW<=bounds.maxX+.01;x+=cellW){const cell={x,y,w:cellW,h:cellH};if(boxInside(cell,poly)&&!forbidden.some(r=>overlaps(cell,r)))cells.push(cell)}
  const used=new Set<number>();let totalBudget=targetArea;
  selected.forEach(name=>{const min=minimum(name),desired=targetArea>=minTotal?min+extra/selected.length:Math.min(totalBudget,min);if(desired<min)return;totalBudget-=desired;let remaining=desired;for(let i=0;i<cells.length&&remaining>=Math.min(150,min);i++){if(used.has(i))continue;const base=cells[i],area=Math.min(remaining,base.w*base.h),h=area/base.w,candidate={...base,h};if(h<6||!boxInside(candidate,poly)||boxes.some(b=>overlaps(candidate,b)))continue;used.add(i);remaining-=area;const park=PARK_NAMES.has(name),utility=UTILITY_NAMES.has(name),color=park?COLORS.park:utility?COLORS.utility:name==="Commercial Block"?COLORS.commercial:COLORS.amenity;boxes.push({...candidate,name,color})}});
  return boxes;
}

function generateLayout(points:SurveyPoint[],plotTypes:PlotType[],selected:AmenityKey[],mainRoad:number,internalRoad:number,numberingStart:number,advancedMode:boolean,adjustmentTolerance:number,strategy:DevelopmentStrategy,plotPct:number,amenityPct:number,roadPct:number,autoRoad:boolean){
  const survey=advancedMode?surveyPolygon(points):approximatePolygon(points),poly=survey.poly,gross=polygonArea(poly),xs=poly.map(p=>p.x),ys=poly.map(p=>p.y),bounds={minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys)};
  const active=plotTypes.filter(p=>p.allocation>0&&p.width>0&&p.depth>0).sort((a,b)=>b.allocation-a.allocation),preferredDepth=active[0]?.depth||40;
  const bw=bounds.maxX-bounds.minX,bh=bounds.maxY-bounds.minY,roadX=bounds.minX+bw*.5,bandDepth=strategy==="Premium Development"?Math.max(preferredDepth,50):preferredDepth,accessBranches=Math.max(1,Math.round(bh/(bandDepth*2+internalRoad))),maxBranches=Math.max(1,Math.floor(bh/(40+internalRoad))),roadAreaFor=(count:number)=>{const pitch=bh/count,ys=Array.from({length:count},(_,i)=>bounds.minY+pitch*(i+.5)),main={x:roadX-mainRoad/2,y:bounds.minY,w:mainRoad,h:bh};return boxPolygonArea(main,poly)+ys.reduce((s,y)=>s+boxPolygonArea({x:bounds.minX,y:y-internalRoad/2,w:bw,h:internalRoad},poly)-boxPolygonArea({x:main.x,y:y-internalRoad/2,w:main.w,h:internalRoad},poly),0)},manualBranches=Array.from({length:maxBranches},(_,i)=>i+1).reduce((best,n)=>Math.abs(roadAreaFor(n)-gross*roadPct/100)<Math.abs(roadAreaFor(best)-gross*roadPct/100)?n:best,1),branchCount=autoRoad?accessBranches:manualBranches,roadPitch=bh/branchCount,rowDepth=Math.max(20,(roadPitch-internalRoad)/2),internalRoadYs=Array.from({length:branchCount},(_,i)=>bounds.minY+roadPitch*(i+.5));
  const roadBoxes:Box[]=[{x:roadX-mainRoad/2,y:bounds.minY,w:mainRoad,h:bh},...internalRoadYs.map(y=>({x:bounds.minX,y:y-internalRoad/2,w:bw,h:internalRoad}))];
  const roadArea=Math.min(gross,roadBoxes.reduce((s,b)=>s+boxPolygonArea(b,poly),0)-internalRoadYs.reduce((s,y)=>s+boxPolygonArea({x:roadX-mainRoad/2,y:y-internalRoad/2,w:mainRoad,h:internalRoad},poly),0)),nonRoad=Math.max(0,gross-roadArea),weightTotal=Math.max(.0001,plotPct+amenityPct),targetPlotArea=autoRoad?nonRoad*plotPct/weightTotal:gross*plotPct/100,targetAmenityArea=autoRoad?nonRoad*amenityPct/weightTotal:gross*amenityPct/100;
  const spatialAmenities=selected.filter(a=>!["Compound Wall","Main Entrance Arch"].includes(a)),amenityBoxes=makeAmenityBoxes(poly,spatialAmenities,targetAmenityArea,bounds,roadBoxes),unplacedAmenities=spatialAmenities.filter(a=>!amenityBoxes.some(b=>b.name===a));
  const plots:GeneratedPlot[]=[],occupied:Box[]=[...roadBoxes,...amenityBoxes];let number=Math.max(1,Math.round(numberingStart)||101);
  let placedPlotArea=0;const place=(b:Box,t:PlotType,kind:"standard"|"adjusted"|"premium"|"corner"|"odd"|"commercial")=>{const area=b.w*b.h;if(placedPlotArea>=targetPlotArea||placedPlotArea+area>targetPlotArea+Math.max(150,area*.35)||!boxInside(b,poly)||occupied.some(o=>overlaps(b,o)))return false;const touchesMain=Math.abs(b.x+b.w-(roadX-mainRoad/2))<=2||Math.abs(b.x-(roadX+mainRoad/2))<=2,effective=kind==="standard"&&touchesMain?"corner":kind;plots.push({...b,number:number++,type:effective==="odd"?"Odd Plot":effective==="premium"?"Premium Plot":effective==="corner"?"Corner Plot":effective==="commercial"?"Commercial Plot":t.name,width:Number(b.w.toFixed(1)),depth:Number(b.h.toFixed(1)),area,roadAccess:true,adjusted:effective==="adjusted",premium:effective==="premium",corner:effective==="corner",odd:effective==="odd"});placedPlotArea+=area;occupied.push(b);return true};
  const fitAt=(x:number,roadY:number,side:"north"|"south")=>{const yFor=(d:number)=>side==="north"?roadY+internalRoad/2:roadY-internalRoad/2-d;
    for(const t of active){const b={x,y:yFor(t.depth),w:t.width,h:t.depth};if(place(b,t,"standard"))return t.width;}
    for(const t of active)for(const delta of [1,-1,2,-2].filter(v=>Math.abs(v)<=adjustmentTolerance)){for(const [dw,dd] of [[delta,0],[0,delta]]){const w=t.width+dw,d=t.depth+dd;if(w>=18&&d>=20&&place({x,y:yFor(d),w,h:d},t,"adjusted"))return w;}}
    for(const [w,d] of [[30,45],[30,50],[35,40],[40,40]])if(d<=rowDepth+2&&place({x,y:yFor(d),w,h:d},{id:-2,name:"Premium Plot",width:w,depth:d,allocation:0},"premium"))return w;
    if(selected.includes("Commercial Block"))for(const [w,d] of [[40,50],[30,40]])if(d<=rowDepth+2&&place({x,y:yFor(d),w,h:d},{id:-3,name:"Commercial Plot",width:w,depth:d,allocation:0},"commercial"))return w;
    const nearJunction=Math.abs(x-(roadX-mainRoad/2))<45;for(let w=50;w>=12;w--){for(let d=Math.floor(Math.min(65,rowDepth));d>=15;d--){const t={id:-1,name:"Odd Plot",width:w,depth:d,allocation:0};if(place({x,y:yFor(d),w,h:d},t,nearJunction?"corner":"odd"))return w;}}
    return 0};
  if(active.length)internalRoadYs.forEach(roadY=>(["north","south"] as const).forEach(side=>{let x=bounds.minX,guard=0;while(x<bounds.maxX-12&&guard++<1500){const used=fitAt(x,roadY,side);x+=used||1;}}));
  internalRoadYs.forEach(roadY=>(["north","south"] as const).forEach(side=>{const front=side==="north"?roadY+internalRoad/2:roadY-internalRoad/2,back=side==="north"?Math.min(bounds.maxY,front+rowDepth):Math.max(bounds.minY,front-rowDepth),low=Math.min(front,back),high=Math.max(front,back),frontSpan=horizontalSpan(poly,front+(side==="north"?.01:-.01)),backSpan=horizontalSpan(poly,back+(side==="north"?-.01:.01)),row=plots.filter(p=>p.y<high-.01&&p.y+p.h>low+.01);if(!frontSpan||!backSpan||!row.length)return;const first=Math.min(...row.map(p=>p.x)),last=Math.max(...row.map(p=>p.x+p.w));const addEdge=(shape:XY[])=>{const area=polygonArea(shape),x0=Math.min(...shape.map(p=>p.x)),x1=Math.max(...shape.map(p=>p.x)),y0=Math.min(...shape.map(p=>p.y)),y1=Math.max(...shape.map(p=>p.y)),box={x:x0,y:y0,w:x1-x0,h:y1-y0};if(area<150||placedPlotArea>=targetPlotArea||placedPlotArea+area>targetPlotArea+area*.35||amenityBoxes.some(a=>overlaps(box,a)))return;plots.push({...box,shape,number:number++,type:"Odd Plot",width:Number(box.w.toFixed(1)),depth:Number(box.h.toFixed(1)),area,roadAccess:true,adjusted:false,premium:false,corner:false,odd:true});placedPlotArea+=area};if(first-frontSpan.min>4&&first<roadX-mainRoad/2)addEdge([{x:frontSpan.min,y:front},{x:first,y:front},{x:first,y:back},{x:backSpan.min,y:back}]);if(frontSpan.max-last>4&&last>roadX+mainRoad/2)addEdge([{x:last,y:front},{x:frontSpan.max,y:front},{x:backSpan.max,y:back},{x:last,y:back}])}));
  const saleableArea=plots.reduce((s,p)=>s+p.area,0),adjustedPlotArea=plots.filter(p=>p.adjusted).reduce((s,p)=>s+p.area,0),premiumPlotArea=plots.filter(p=>p.premium).reduce((s,p)=>s+p.area,0),cornerPlotArea=plots.filter(p=>p.corner).reduce((s,p)=>s+p.area,0),oddPlotArea=plots.filter(p=>p.odd).reduce((s,p)=>s+p.area,0);
  const parkArea=amenityBoxes.filter(a=>PARK_NAMES.has(a.name)).reduce((s,a)=>s+a.w*a.h,0),utilityArea=amenityBoxes.filter(a=>UTILITY_NAMES.has(a.name)).reduce((s,a)=>s+a.w*a.h,0),amenityArea=amenityBoxes.filter(a=>!PARK_NAMES.has(a.name)&&!UTILITY_NAMES.has(a.name)).reduce((s,a)=>s+a.w*a.h,0),allocated=gross?Math.min(gross,roadArea+saleableArea+parkArea+utilityArea+amenityArea):0,unusedArea=Math.max(0,gross-allocated),landscapeArea=selected.includes("Landscape Area")?unusedArea:0;
  return{...survey,poly,gross,bounds,bw,bh,roadX,internalRoadYs,roadArea,parkArea,amenityArea,utilityArea,plots,amenityBoxes,unplacedAmenities,saleableArea,adjustedPlotArea,premiumPlotArea,cornerPlotArea,oddPlotArea,landscapeArea,unusedArea,roadLength:bh+bw*internalRoadYs.length,advancedMode,strategy,targetPlotArea,targetAmenityArea,actualAmenityArea:parkArea+utilityArea+amenityArea,autoRoad};
}

function buildBoq(layout:ReturnType<typeof generateLayout>,selected:AmenityKey[]):BoqRow[]{
  const has=(n:AmenityKey)=>selected.includes(n),r=(category:string,item:string,qty:number,unit:string,rate:number):BoqRow=>({category,item,qty,unit,rate,amount:qty*rate});
  return[
    r("Preliminaries","Site clearing",layout.gross,"sqft",4),r("Earthwork","Earthwork and levelling",layout.gross*.35,"cft",18),
    r("Road Works","Main road formation",layout.bh,"rft",2200),r("Road Works","Internal road formation",layout.bw*layout.internalRoadYs.length,"rft",1450),r("Road Works","WMM / base course",layout.roadArea,"sqft",85),r("Road Works","Asphalt / concrete road",layout.roadArea,"sqft",120),
    r("Drainage","Side drains",layout.roadLength*2,"rft",450),r("Drainage","Culverts",Math.max(2,Math.ceil(layout.roadLength/1200)),"nos",75000),
    r("Water Supply","Water supply lines",layout.roadLength,"rft",280),r("Sewerage","Sewer lines",layout.roadLength,"rft",360),
    r("Utilities","STP",has("STP")?1:0,"LS",1800000),r("Utilities","Underground tank",has("UG Tank")?1:0,"LS",950000),
    r("Site Works","Compound wall",has("Compound Wall")?perimeter(layout.poly):0,"rft",1200),r("Site Works","Entrance arch",has("Main Entrance Arch")?1:0,"nos",800000),
    r("Electrical","Street lights",Math.ceil(layout.roadLength/100),"nos",30000),r("Electrical","Transformer yard",has("Transformer Yard")?1:0,"LS",1200000),
    r("Amenities","Club house",has("Club House")?layout.gross*.015:0,"sqft",2500),r("Amenities","Swimming pool",has("Swimming Pool")?layout.gross*.008:0,"sqft",1800),r("Amenities","Parks / landscape",has("Landscape Area")?layout.parkArea+layout.landscapeArea:has("Park")?layout.parkArea:0,"sqft",120),r("Amenities","Security cabin",has("Security Cabin")?300:0,"sqft",2200)
  ];
}

function LayoutSvg({layout,mainRoad,internalRoad,selected}:{layout:ReturnType<typeof generateLayout>;mainRoad:number;internalRoad:number;selected:AmenityKey[]}){
  const {bounds,bw,bh}=layout,pad=70,scale=Math.min(820/(bw||1),560/(bh||1)),sx=(x:number)=>pad+(x-bounds.minX)*scale,sy=(y:number)=>pad+(bounds.maxY-y)*scale,path=layout.poly.map((p,i)=>(i?"L":"M")+sx(p.x)+","+sy(p.y)).join(" ")+" Z";
  const roadYs=layout.internalRoadYs.map(sy),roadX=sx(layout.roadX),mainW=mainRoad*scale,internalH=internalRoad*scale,types=[...new Set(layout.plots.filter(p=>!p.odd).map(p=>p.type))],palette=["#fef3c7","#fde68a","#dbeafe","#e0e7ff","#fce7f3","#dcfce7"];
  return <svg id="layout-svg" viewBox="0 0 960 720" width="100%" style={{minWidth:760,display:"block"}} role="img" aria-label="Generated zero-waste land development layout">
    <defs><clipPath id="siteClip"><path d={path}/></clipPath></defs><rect width="960" height="720" fill="#fffef9"/>
    <text x="24" y="28" fontSize="16" fontWeight="800">BUILDMITRA — LAND DEVELOPMENT MASTER LAYOUT</text><text x="24" y="45" fontSize="8" fill="#64748b">PLOTTED DEVELOPMENT • ROAD-FRONT SITES • ALL DIMENSIONS IN FEET • VERIFY WITH LICENSED TOWN PLANNER</text>
    <g transform="translate(900 62)"><text y="-24" textAnchor="middle" fontSize="13" fontWeight="800">N</text><path d="M0,-18 L-9,9 L0,4 L9,9 Z" fill="#1f2937"/><line y1="-18" y2="25" stroke="#1f2937"/></g>
    <g clipPath="url(#siteClip)"><path d={path} fill="#ecfccb"/><text x={pad+bw*scale*.18} y={pad+bh*scale*.92} fontSize="8" fill="#3f6212">LANDSCAPE / UTILITY POCKETS</text><rect x={roadX-mainW/2} y={pad} width={mainW} height={bh*scale} fill={COLORS.road}/>{roadYs.map((y,i)=><rect key={i} x={pad} y={y-internalH/2} width={bw*scale} height={internalH} fill="#94a3b8"/>)}
      <line x1={roadX} y1={pad} x2={roadX} y2={pad+bh*scale} stroke="white" strokeDasharray="12 8"/>{roadYs.map((y,i)=><line key={i} x1={pad} y1={y} x2={pad+bw*scale} y2={y} stroke="white" strokeDasharray="10 7"/>)}
      <g stroke="#0ea5e9" strokeWidth="2" strokeDasharray="5 3"><line x1={roadX-mainW/2+3} y1={pad} x2={roadX-mainW/2+3} y2={pad+bh*scale}/><line x1={roadX+mainW/2-3} y1={pad} x2={roadX+mainW/2-3} y2={pad+bh*scale}/>{roadYs.flatMap((y,i)=>[<line key={`${i}a`} x1={pad} y1={y-internalH/2+3} x2={pad+bw*scale} y2={y-internalH/2+3}/>,<line key={`${i}b`} x1={pad} y1={y+internalH/2-3} x2={pad+bw*scale} y2={y+internalH/2-3}/>])}</g>
      {layout.amenityBoxes.map((a,i)=>{const first=layout.amenityBoxes.findIndex(b=>b.name===a.name)===i;return <g key={i}>{first&&selected.includes("Jogging Track")&&PARK_NAMES.has(a.name)&&<rect x={sx(a.x)-4} y={sy(a.y+a.h)-4} width={a.w*scale+8} height={a.h*scale+8} fill="none" stroke="#15803d" strokeWidth="3" strokeDasharray="6 3"/>}<rect x={sx(a.x)} y={sy(a.y+a.h)} width={a.w*scale} height={a.h*scale} fill={a.color} stroke={first?"#334155":a.color}/>{first&&<text x={sx(a.x+a.w/2)} y={sy(a.y+a.h/2)} textAnchor="middle" fontSize={Math.max(5,Math.min(9,a.w*scale/10))} fontWeight="700">{a.name.toUpperCase()}</text>}</g>})}
      {layout.plots.map(p=>{const fill=p.odd?"#fda4af":p.corner?"#c4b5fd":p.premium?"#93c5fd":p.adjusted?"#fdba74":palette[Math.max(0,types.indexOf(p.type))%palette.length];return <g key={p.number}>{p.shape?<polygon points={p.shape.map(v=>`${sx(v.x)},${sy(v.y)}`).join(" ")} fill={fill} stroke={COLORS.plotStroke} strokeWidth=".8"/>:<rect x={sx(p.x)} y={sy(p.y+p.h)} width={p.w*scale} height={p.h*scale} fill={fill} stroke={COLORS.plotStroke} strokeWidth=".8"/>}<text x={sx(p.x+p.w/2)} y={sy(p.y+p.h/2)-6} textAnchor="middle" fontSize="7" fontWeight="800">{p.number}</text><text x={sx(p.x+p.w/2)} y={sy(p.y+p.h/2)+2} textAnchor="middle" fontSize="5.5">{p.shape?`${num(p.area)} sqft`:`${p.width}×${p.depth}`}</text><text x={sx(p.x+p.w/2)} y={sy(p.y+p.h/2)+10} textAnchor="middle" fontSize="4.8" fontWeight="800">{p.odd?"ODD PLOT":p.corner?"CORNER PLOT":p.premium?"PREMIUM PLOT":p.adjusted?"ADJUSTED PLOT":p.type}</text></g>})}
    </g>
    <path d={path} fill="none" stroke="#111827" strokeWidth={selected.includes("Compound Wall")?4:2}/>{layout.poly.map((p,i)=><g key={i}><circle cx={sx(p.x)} cy={sy(p.y)} r="4" fill="#7f1d1d"/><text x={sx(p.x)+6} y={sy(p.y)-6} fontSize="8" fontWeight="800">{String.fromCharCode(65+i)}</text></g>)}
    <g><line x1={pad} y1={pad+bh*scale+22} x2={pad+bw*scale} y2={pad+bh*scale+22} stroke="#334155"/><text x={pad+bw*scale/2} y={pad+bh*scale+37} textAnchor="middle" fontSize="8">BOUNDING WIDTH {num(bw,1)} ft</text><line x1={pad-22} y1={pad} x2={pad-22} y2={pad+bh*scale} stroke="#334155"/><text x={pad-36} y={pad+bh*scale/2} transform={`rotate(-90 ${pad-36} ${pad+bh*scale/2})`} textAnchor="middle" fontSize="8">BOUNDING LENGTH {num(bh,1)} ft</text></g>
    <text x={roadX+8} y={pad+bh*scale*.88} transform={`rotate(-90 ${roadX+8} ${pad+bh*scale*.88})`} textAnchor="middle" fontSize="8" fill="white" fontWeight="800">MAIN ROAD • {mainRoad} FT</text>{roadYs.map((y,i)=><text key={i} x={pad+bw*scale*.78} y={y+4} textAnchor="middle" fontSize="7" fill="white">INTERNAL ROAD {i+1} • {internalRoad} FT</text>)}
    {selected.includes("Main Entrance Arch")&&<g><line x1={roadX-mainW/2} y1={pad+bh*scale} x2={roadX+mainW/2} y2={pad+bh*scale} stroke="white" strokeWidth="8"/><path d={`M${roadX-mainW/2},${pad+bh*scale} Q${roadX},${pad+bh*scale-34} ${roadX+mainW/2},${pad+bh*scale}`} fill="none" stroke="#7f1d1d" strokeWidth="4"/><text x={roadX} y={pad+bh*scale-40} textAnchor="middle" fontSize="8" fontWeight="800">MAIN ENTRANCE ARCH</text></g>}
    <g transform="translate(590 604)" fontSize="7"><rect width="330" height="92" fill="white" stroke="#cbd5e1"/><rect x="10" y="9" width="16" height="10" fill={COLORS.plot}/><text x="32" y="17">Standard</text><rect x="95" y="9" width="16" height="10" fill="#fdba74"/><text x="117" y="17">Adjusted</text><rect x="185" y="9" width="16" height="10" fill="#93c5fd"/><text x="207" y="17">Premium</text><rect x="270" y="9" width="16" height="10" fill="#c4b5fd"/><text x="292" y="17">Corner</text><rect x="10" y="31" width="16" height="10" fill="#fda4af"/><text x="32" y="39">Odd plots</text><rect x="95" y="31" width="16" height="10" fill={COLORS.road}/><text x="117" y="39">Roads</text><rect x="185" y="31" width="16" height="10" fill={COLORS.park}/><text x="207" y="39">Open space</text><rect x="270" y="31" width="16" height="10" fill={COLORS.amenity}/><text x="292" y="39">Amenities</text><line x1="10" y1="60" x2="30" y2="60" stroke="#0ea5e9" strokeWidth="2" strokeDasharray="4 2"/><text x="36" y="63">Road-side drainage</text><text x="10" y="81" fontWeight="800">Strategy: {layout.strategy}</text></g>
  </svg>;
}

const ui:Record<string,React.CSSProperties>={page:{minHeight:"100vh",background:"#eef2f6",padding:16,color:"#1f2937"},header:{background:"linear-gradient(135deg,#3f0d22,#7f1d1d)",color:"white",padding:"18px 22px",borderRadius:14,display:"flex",justifyContent:"space-between",alignItems:"center",gap:12},card:{background:"white",padding:16,borderRadius:12,boxShadow:"0 3px 14px rgba(15,23,42,.08)",marginTop:14},grid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(175px,1fr))",gap:10},input:{width:"100%",boxSizing:"border-box",padding:"8px 9px",border:"1px solid #cbd5e1",borderRadius:7},label:{fontSize:10,fontWeight:800,textTransform:"uppercase",display:"block",marginBottom:4,color:"#475569"},table:{width:"100%",borderCollapse:"collapse",fontSize:11,minWidth:760},th:{background:"#f1f5f9",padding:8,border:"1px solid #dbe3ea",textAlign:"left"},td:{padding:7,border:"1px solid #dbe3ea"},button:{border:0,borderRadius:7,padding:"9px 14px",background:"#7f1d1d",color:"white",fontWeight:800,cursor:"pointer"},metric:{padding:12,borderRadius:9,background:"#f8fafc",border:"1px solid #e2e8f0"},warning:{padding:10,background:"#fff7ed",color:"#9a3412",border:"1px solid #fdba74",borderRadius:8,marginTop:8,fontSize:11,fontWeight:700}};
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span style={ui.label}>{label}</span>{children}</label>}
function TableWrap({children}:{children:React.ReactNode}){return <div style={{overflowX:"auto"}}>{children}</div>}

export default function LayoutPlansPage(){
  const router=useRouter();
  const [points,setPoints]=useState<SurveyPoint[]>([{id:1,name:"A",distance:960,bearing:180},{id:2,name:"B",distance:1150,bearing:270},{id:3,name:"C",distance:213,bearing:0},{id:4,name:"D",distance:890,bearing:90}]);
  const [plotTypes,setPlotTypes]=useState<PlotType[]>([{id:1,name:"30×40",width:30,depth:40,allocation:45},{id:2,name:"30×50",width:30,depth:50,allocation:20},{id:3,name:"40×60",width:40,depth:60,allocation:25},{id:4,name:"50×80",width:50,depth:80,allocation:10}]);
  const [mainRoad,setMainRoad]=useState(20),[internalRoad,setInternalRoad]=useState(15),[numberingStart,setNumberingStart]=useState(101),[projectType,setProjectType]=useState("Residential Layout"),[landCost,setLandCost]=useState(8500000),[sellingPrice,setSellingPrice]=useState(1800),[contingencyPct,setContingencyPct]=useState(5),[advancedMode,setAdvancedMode]=useState(false),[adjustmentTolerance,setAdjustmentTolerance]=useState(2),[strategy,setStrategy]=useState<DevelopmentStrategy>("User Controlled Allocation"),[plotPct,setPlotPct]=useState(80),[amenityPct,setAmenityPct]=useState(5),[roadPct,setRoadPct]=useState(15),[autoRoad,setAutoRoad]=useState(true);
  const [selected,setSelected]=useState<AmenityKey[]>(["Park","Children Park","STP","UG Tank","Overhead Tank","Security Cabin","Visitors Parking","Compound Wall","Main Entrance Arch","Transformer Yard","Rain Water Harvesting","Landscape Area"]);
  const [generated,setGenerated]=useState<null|{points:SurveyPoint[];plotTypes:PlotType[];selected:AmenityKey[];mainRoad:number;internalRoad:number;numberingStart:number;projectType:string;landCost:number;sellingPrice:number;contingencyPct:number;advancedMode:boolean;adjustmentTolerance:number;strategy:DevelopmentStrategy;plotPct:number;amenityPct:number;roadPct:number;autoRoad:boolean}>(null);
  const layout=useMemo(()=>generated?generateLayout(generated.points,generated.plotTypes,generated.selected,generated.mainRoad,generated.internalRoad,generated.numberingStart,generated.advancedMode,generated.adjustmentTolerance,generated.strategy,generated.plotPct,generated.amenityPct,generated.roadPct,generated.autoRoad):null,[generated]);
  const boq=useMemo(()=>layout&&generated?buildBoq(layout,generated.selected):[],[layout,generated]);
  const allocationTotal=plotTypes.reduce((s,p)=>s+p.allocation,0),landAllocationTotal=plotPct+amenityPct+(autoRoad?0:roadPct),manualAllocationValid=autoRoad||Math.abs(landAllocationTotal-100)<.01,warnings:string[]=[];
  if(generated&&layout){if(!generated.advancedMode)warnings.push("Approximate boundary generated. Use Advanced Survey Mode for survey-accurate layout.");if(layout.unplacedAmenities.length)warnings.push(`Amenity allocation is insufficient or cannot fit usable sizes for: ${layout.unplacedAmenities.join(", ")}.`);if(layout.targetAmenityArea>0&&!generated.selected.filter(a=>!["Compound Wall","Main Entrance Arch"].includes(a)).length)warnings.push("Amenity percentage is greater than zero, but no area-based amenity is selected.");if(layout.actualAmenityArea+1<layout.targetAmenityArea*.9)warnings.push(`Only ${num(layout.actualAmenityArea)} sqft of the ${num(layout.targetAmenityArea)} sqft amenity allocation could be placed. Review amenity selection or site geometry.`);if(layout.saleableArea+1<layout.targetPlotArea*.9)warnings.push(`Only ${num(layout.saleableArea)} sqft of the ${num(layout.targetPlotArea)} sqft plot allocation could be fitted with road access.`);if(Math.abs(generated.plotTypes.reduce((s,p)=>s+p.allocation,0)-100)>.1)warnings.push("Plot mix allocation must total 100%.");if(layout.plots.some(p=>!p.roadAccess))warnings.push("One or more plots do not have road access.");if(!generated.autoRoad&&Math.abs(layout.roadArea-layout.gross*generated.roadPct/100)>layout.gross*.03)warnings.push("Actual access-road geometry differs from the manual road allocation by more than 3%. Road access rules take priority.");if(generated.advancedMode&&layout.closureError>5)warnings.push(`Survey closure differs by ${num(layout.closureError,1)} ft. Verify the final edge distance/bearing.`)}
  const boqTotal=boq.reduce((s,r)=>s+r.amount,0),amenityCost=boq.filter(r=>r.category==="Amenities").reduce((s,r)=>s+r.amount,0),developmentCost=boqTotal-amenityCost;
  const acres=layout?layout.gross/43560:0,landPurchase=generated?acres*generated.landCost:0,revenue=layout&&generated?layout.saleableArea*generated.sellingPrice:0,approval=(landPurchase+developmentCost)*.025,contingency=(developmentCost+amenityCost)*(generated?.contingencyPct||0)/100,totalCost=landPurchase+developmentCost+amenityCost+approval+contingency,grossProfit=revenue-landPurchase-developmentCost-amenityCost,netProfit=revenue-totalCost;
  const utilizationPct=layout&&layout.gross?(layout.roadArea+layout.amenityArea+layout.utilityArea+layout.parkArea+layout.saleableArea)/layout.gross*100:0;
  const updatePoint=(id:number,key:keyof SurveyPoint,value:string|number)=>setPoints(rows=>rows.map(r=>r.id===id?{...r,[key]:key==="name"?value:Number(value)}:r));
  const updatePlot=(id:number,key:keyof PlotType,value:string|number)=>setPlotTypes(rows=>rows.map(r=>r.id===id?{...r,[key]:key==="name"?value:Number(value)}:r));
  const addPoint=()=>setPoints(rows=>[...rows,{id:Date.now(),name:String.fromCharCode(65+rows.length),distance:300,bearing:(rows.length*360/(rows.length+1))%360}]);
  const addPlot=()=>setPlotTypes(rows=>[...rows,{id:Date.now(),name:"Custom",width:30,depth:40,allocation:0}]);
  const applyStrategy=(value:DevelopmentStrategy)=>{setStrategy(value);if(value==="Maximize Plots"){setPlotPct(90);setAmenityPct(5);setAutoRoad(true)}else if(value==="Balanced Development"){setPlotPct(70);setAmenityPct(15);setAutoRoad(true)}else if(value==="Premium Development"){setPlotPct(55);setAmenityPct(30);setAutoRoad(true)}};
  const generate=()=>{if(!manualAllocationValid)return;setGenerated({points:points.map(p=>({...p})),plotTypes:plotTypes.map(p=>({...p})),selected:[...selected],mainRoad,internalRoad,numberingStart,projectType,landCost,sellingPrice,contingencyPct,advancedMode,adjustmentTolerance,strategy,plotPct,amenityPct,roadPct,autoRoad})};
  const exportPng=()=>{const svg=document.getElementById("layout-svg") as unknown as SVGSVGElement|null;if(!svg)return;const canvas=document.createElement("canvas"),ctx=canvas.getContext("2d"),image=new Image();canvas.width=1920;canvas.height=1440;image.onload=()=>{ctx?.drawImage(image,0,0,canvas.width,canvas.height);const link=document.createElement("a");link.download=`zero-waste-layout-${Date.now()}.png`;link.href=canvas.toDataURL("image/png");link.click()};image.src="data:image/svg+xml;charset=utf-8,"+encodeURIComponent(new XMLSerializer().serializeToString(svg))};
  const exportPdf=()=>{if(!layout||!generated)return;const doc=new jsPDF();doc.setFontSize(16);doc.text("BuildMitra Zero-Waste Land Layout",14,18);doc.setFontSize(10);[["Gross area",`${num(layout.gross)} sqft`],["Road area",`${num(layout.roadArea)} sqft`],["Saleable plots",`${num(layout.saleableArea)} sqft`],["Land utilization",`${num(utilizationPct,2)}%`],["Plots",String(layout.plots.length)],["Development cost",money(developmentCost)],["Net profit",money(netProfit)]].forEach((row,i)=>doc.text(`${row[0]}: ${row[1]}`,14,32+i*8));doc.save(`zero-waste-layout-${Date.now()}.pdf`)};
  const exportExcel=()=>{if(!layout||!generated)return;const workbook=XLSX.utils.book_new(),areaRows=[{"Area Category":"Gross Land","Sqft":layout.gross},{"Area Category":"Roads","Sqft":layout.roadArea},{"Area Category":"Amenities","Sqft":layout.amenityArea},{"Area Category":"Utilities","Sqft":layout.utilityArea},{"Area Category":"Park/Open","Sqft":layout.parkArea},{"Area Category":"Saleable Plots","Sqft":layout.saleableArea},{"Area Category":"Adjusted Plots","Sqft":layout.adjustedPlotArea},{"Area Category":"Premium Plots","Sqft":layout.premiumPlotArea},{"Area Category":"Corner Plots","Sqft":layout.cornerPlotArea},{"Area Category":"Odd Plots","Sqft":layout.oddPlotArea},{"Area Category":"Unused Area","Sqft":layout.unusedArea}];XLSX.utils.book_append_sheet(workbook,XLSX.utils.json_to_sheet(areaRows),"Area Statement");XLSX.utils.book_append_sheet(workbook,XLSX.utils.json_to_sheet(layout.plots.map(p=>({"Plot No":p.number,"Plot Size":`${p.width}x${p.depth}`,"Plot Area":p.area,"Plot Type":p.odd?"Odd Plot":p.corner?"Corner Plot":p.premium?"Premium Plot":p.adjusted?"Adjusted Plot":p.type,"Road Access":p.roadAccess?"Yes":"No"}))),"Plot Schedule");XLSX.utils.book_append_sheet(workbook,XLSX.utils.json_to_sheet(boq),"BOQ");XLSX.writeFile(workbook,`zero-waste-layout-${Date.now()}.xlsx`)};
  return <main style={ui.page}>
    <header style={ui.header}><div><h1 style={{margin:0,fontSize:22}}>BuildMitra LAND DEVELOPMENT LAYOUT PLANNING SYSTEM</h1><p style={{margin:"5px 0 0",fontSize:12,opacity:.88}}>Survey polygon • plotted development roads • numbered sites • infrastructure BOQ • developer feasibility</p></div><button onClick={()=>router.push("/")} style={{...ui.button,background:"rgba(255,255,255,.14)"}}>← Home</button></header>
    <section style={ui.card}><h2 style={{marginTop:0}}>1. Survey Boundary / Polygon Inputs</h2><p style={{fontSize:11,color:"#64748b"}}>Normal Mode uses all side lengths to create a closed best-fit quadrilateral/trapezium or multi-side polygon. Enable Advanced Survey Mode only when verified survey bearings are available.</p>
      <label style={{display:"flex",gap:7,alignItems:"center",fontSize:12,fontWeight:800,marginBottom:10}}><input type="checkbox" checked={advancedMode} onChange={e=>setAdvancedMode(e.target.checked)}/> Advanced Survey Mode — show bearings</label>
      <TableWrap><table style={ui.table}><thead><tr><th style={ui.th}>Boundary Side</th><th style={ui.th}>Distance to next point (ft)</th>{advancedMode&&<th style={ui.th}>Direction / Bearing (°)</th>}<th style={ui.th}>Action</th></tr></thead><tbody>{points.map((p,i)=><tr key={p.id}><td style={ui.td}><input value={p.name} onChange={e=>updatePoint(p.id,"name",e.target.value)} style={ui.input}/><small style={{display:"block",color:i===0?"#166534":"#64748b"}}>Side {p.name}-{points[(i+1)%points.length]?.name}{i===0?" • NE reference":""}</small></td><td style={ui.td}><input type="number" min="1" value={p.distance} onChange={e=>updatePoint(p.id,"distance",e.target.value)} style={ui.input}/></td>{advancedMode&&<td style={ui.td}><input type="number" min="0" max="359" value={p.bearing} onChange={e=>updatePoint(p.id,"bearing",e.target.value)} style={ui.input}/></td>}<td style={ui.td}><button disabled={points.length<=3} onClick={()=>setPoints(rows=>rows.filter(x=>x.id!==p.id))}>Remove</button></td></tr>)}</tbody></table></TableWrap><button onClick={addPoint} style={{...ui.button,marginTop:9}}>+ Add Boundary Side</button>
    </section>
    <section style={ui.card}><h2 style={{marginTop:0}}>2. Land Development & Plot Configuration</h2><div style={ui.grid}>
      <Field label="Development Strategy"><select value={strategy} onChange={e=>applyStrategy(e.target.value as DevelopmentStrategy)} style={ui.input}>{["Maximize Plots","Balanced Development","Premium Development","User Controlled Allocation"].map(v=><option key={v}>{v}</option>)}</select></Field>
      <Field label="Road Configuration (Main / Internal)"><select value={`${mainRoad}/${internalRoad}`} onChange={e=>{const [main,internal]=e.target.value.split("/").map(Number);setMainRoad(main);setInternalRoad(internal)}} style={ui.input}>{["20/15","25/20","30/25","40/30"].map(v=><option key={v} value={v}>{v.replace("/"," / ")} ft</option>)}</select></Field>
      <Field label="Plot Numbering Start"><input type="number" value={numberingStart} onChange={e=>setNumberingStart(Number(e.target.value))} style={ui.input}/></Field>
      <Field label="Project Type"><select value={projectType} onChange={e=>setProjectType(e.target.value)} style={ui.input}>{["Residential Layout","Villa Layout","Farm Plots","Mixed Development"].map(v=><option key={v}>{v}</option>)}</select></Field>
      <Field label="Land Cost / Acre"><input type="number" value={landCost} onChange={e=>setLandCost(Number(e.target.value))} style={ui.input}/></Field>
      <Field label="Selling Price / sqft"><input type="number" value={sellingPrice} onChange={e=>setSellingPrice(Number(e.target.value))} style={ui.input}/></Field>
      <Field label="Development Contingency %"><input type="number" min="0" max="25" value={contingencyPct} onChange={e=>setContingencyPct(Number(e.target.value))} style={ui.input}/></Field>
      <Field label="Plot Adjustment Tolerance"><select value={adjustmentTolerance} onChange={e=>setAdjustmentTolerance(Number(e.target.value))} style={ui.input}><option value={1}>± 1 ft</option><option value={2}>± 2 ft</option></select></Field>
    </div>
      <h3>Land Allocation</h3><div style={ui.grid}>
        <Field label="Plots %"><input type="number" min="0" max="100" value={plotPct} onChange={e=>{setPlotPct(Math.max(0,Number(e.target.value)));setStrategy("User Controlled Allocation")}} style={ui.input}/></Field>
        <Field label="Amenities %"><input type="number" min="0" max="100" value={amenityPct} onChange={e=>{setAmenityPct(Math.max(0,Number(e.target.value)));setStrategy("User Controlled Allocation")}} style={ui.input}/></Field>
        <Field label="Roads %"><input type="number" min="0" max="100" value={autoRoad&&layout?Number((layout.roadArea/layout.gross*100).toFixed(2)):roadPct} disabled={autoRoad} onChange={e=>{setRoadPct(Math.max(0,Number(e.target.value)));setStrategy("User Controlled Allocation")}} style={{...ui.input,background:autoRoad?"#f1f5f9":"white"}}/></Field>
        <label style={{display:"flex",gap:8,alignItems:"center",fontSize:12,fontWeight:800,paddingTop:18}}><input type="checkbox" checked={autoRoad} onChange={e=>{setAutoRoad(e.target.checked);setStrategy("User Controlled Allocation")}}/> Auto Calculate Roads</label>
      </div>
      <div style={{...ui.warning,background:manualAllocationValid?"#f0fdf4":"#fef2f2",color:manualAllocationValid?"#166534":"#b91c1c",borderColor:manualAllocationValid?"#86efac":"#fca5a5"}}>{autoRoad?`Road area will be calculated from the ${mainRoad}/${internalRoad} ft road geometry. Plot and amenity percentages act as relative allocation weights for the remaining land.`:`Manual allocation total: ${num(landAllocationTotal,2)}%. Plots + Amenities + Roads must equal 100%.`}</div>
      <h3>Plot Mix <span style={{fontSize:11,color:Math.abs(allocationTotal-100)<.1?"#166534":"#b91c1c"}}>Allocation total: {allocationTotal}%</span></h3><TableWrap><table style={ui.table}><thead><tr><th style={ui.th}>Plot Type</th><th style={ui.th}>Frontage</th><th style={ui.th}>Depth</th><th style={ui.th}>Allocation %</th><th style={ui.th}>Action</th></tr></thead><tbody>{plotTypes.map(p=><tr key={p.id}><td style={ui.td}><input value={p.name} onChange={e=>updatePlot(p.id,"name",e.target.value)} style={ui.input}/></td><td style={ui.td}><input type="number" value={p.width} onChange={e=>updatePlot(p.id,"width",e.target.value)} style={ui.input}/></td><td style={ui.td}><input type="number" value={p.depth} onChange={e=>updatePlot(p.id,"depth",e.target.value)} style={ui.input}/></td><td style={ui.td}><input type="number" value={p.allocation} onChange={e=>updatePlot(p.id,"allocation",e.target.value)} style={ui.input}/></td><td style={ui.td}><button onClick={()=>setPlotTypes(rows=>rows.filter(x=>x.id!==p.id))}>Remove</button></td></tr>)}</tbody></table></TableWrap><button onClick={addPlot} style={{...ui.button,marginTop:9}}>+ Add Custom Plot</button>
    </section>
    <section style={ui.card}><h2 style={{marginTop:0}}>3. Amenities Selection</h2><p style={{fontSize:11,color:"#64748b"}}>Only checked amenities are generated. Priority follows the selection order; unusable undersized amenities are rejected with a warning.</p><div style={ui.grid}>{AMENITIES.map(a=><label key={a} style={{display:"flex",gap:7,alignItems:"center",fontSize:12}}><input type="checkbox" checked={selected.includes(a)} onChange={e=>setSelected(v=>e.target.checked?[...v,a]:v.filter(x=>x!==a))}/>{a}</label>)}</div><button disabled={!manualAllocationValid} onClick={generate} style={{...ui.button,marginTop:16,padding:"12px 24px",opacity:manualAllocationValid?1:.45}}>Generate Complete Layout</button>{!manualAllocationValid&&<div style={ui.warning}>Cannot generate: Plots + Amenities + Roads must equal 100% in manual road mode.</div>}</section>
    {!layout||!generated?<section style={ui.card}><p style={{margin:0,color:"#64748b"}}>Enter the survey and project requirements, then generate the complete planning report.</p></section>:<>
      {warnings.length>0&&<section style={ui.card}>{warnings.map((w,i)=><div key={i} style={ui.warning}>{w}</div>)}</section>}
      <section style={ui.card}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"center",flexWrap:"wrap"}}><h2 style={{marginTop:0}}>Report 1 — Zero-Waste Layout Drawing</h2><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><button style={ui.button} onClick={exportPng}>Export PNG</button><button style={ui.button} onClick={exportPdf}>Export PDF</button><button style={ui.button} onClick={exportExcel}>Export Excel</button><button style={ui.button} onClick={()=>window.print()}>Print Reports</button></div></div><div style={{overflowX:"auto",border:"1px solid #dbe3ea",borderRadius:8}}><LayoutSvg layout={layout} mainRoad={generated.mainRoad} internalRoad={generated.internalRoad} selected={generated.selected}/></div></section>
      <section style={ui.card}><h2 style={{marginTop:0}}>Report 2 — User-Driven Area Statement</h2><div style={ui.grid}>{[["Gross Land Area",num(layout.gross)+" sqft"],["Gross Acres",num(acres,3)+" acres"],["Gross Guntas",num(acres*40,2)+" guntas"],["Plots Area",num(layout.saleableArea)+` / ${num(layout.targetPlotArea)} sqft target`],["Amenities Area",num(layout.actualAmenityArea)+` / ${num(layout.targetAmenityArea)} sqft target`],["Road Area",num(layout.roadArea)+` sqft (${num(layout.gross?layout.roadArea/layout.gross*100:0,2)}%)`],["Saleable Area",num(layout.saleableArea)+" sqft"],["Adjusted Plot Area",num(layout.adjustedPlotArea)+" sqft"],["Odd Plot Area",num(layout.oddPlotArea)+" sqft"],["Premium Plot Area",num(layout.premiumPlotArea)+" sqft"],["Corner Plot Area",num(layout.cornerPlotArea)+" sqft"],["Utility Area",num(layout.utilityArea)+" sqft"],["Park / Open Space",num(layout.parkArea)+" sqft"],["Unused Area",num(layout.unusedArea)+` sqft (${num(layout.gross?layout.unusedArea/layout.gross*100:0,2)}%)`],["Plot Efficiency",num(layout.targetPlotArea?layout.saleableArea/layout.targetPlotArea*100:100,2)+"%"],["Land Utilization",num(utilizationPct,2)+"%"],["Development Strategy",generated.strategy],["Road Mode",generated.autoRoad?"Auto calculated":"Manual percentage"],["Total Plots",String(layout.plots.length)],["Boundary Mode",generated.advancedMode?"Advanced survey":"Approximate normal"]].map(([k,v])=><div key={k} style={ui.metric}><b>{k}</b><div style={{fontSize:18,marginTop:5}}>{v}</div></div>)}</div></section>
      <section style={ui.card}><h2 style={{marginTop:0}}>Report 3 — Plot Schedule</h2><TableWrap><table style={ui.table}><thead><tr><th style={ui.th}>Plot No.</th><th style={ui.th}>Type</th><th style={ui.th}>Dimensions</th><th style={ui.th}>Status</th><th style={ui.th}>Area</th><th style={ui.th}>Road Access</th></tr></thead><tbody>{layout.plots.map(p=><tr key={p.number}><td style={ui.td}>{p.number}</td><td style={ui.td}>{p.type}</td><td style={ui.td}>{p.width&&p.depth?`${p.width}×${p.depth} ft`:"Measurement unavailable"}</td><td style={ui.td}>{p.odd?"Odd Plot":p.corner?"Corner Plot":p.premium?"Premium Plot":p.adjusted?"Adjusted Plot":"Standard Plot"}</td><td style={ui.td}>{num(p.area)} sqft</td><td style={ui.td}>{p.roadAccess?"Yes":"NO"}</td></tr>)}</tbody></table></TableWrap><h3>Plots by Type</h3><div style={ui.grid}>{generated.plotTypes.map(t=>{const list=layout.plots.filter(p=>p.type===t.name);return <div key={t.id} style={ui.metric}><b>{t.name||"Unnamed Plot Type"}</b><div>{t.width&&t.depth?`${t.width}×${t.depth} ft`:"Measurement unavailable"}</div><div>{list.length} plots • {num(list.reduce((s,p)=>s+p.area,0))} sqft</div></div>})}</div></section>
      <section style={ui.card}><h2 style={{marginTop:0}}>Report 4 — Development BOQ</h2><TableWrap><table style={ui.table}><thead><tr><th style={ui.th}>Category</th><th style={ui.th}>Item</th><th style={ui.th}>Qty</th><th style={ui.th}>Unit</th><th style={ui.th}>Rate</th><th style={ui.th}>Amount</th></tr></thead><tbody>{boq.map((r,i)=><tr key={i}><td style={ui.td}>{r.category}</td><td style={ui.td}>{r.item}</td><td style={ui.td}>{num(r.qty,1)}</td><td style={ui.td}>{r.unit}</td><td style={ui.td}>{money(r.rate)}</td><td style={ui.td}>{money(r.amount)}</td></tr>)}<tr><td colSpan={5} style={{...ui.td,textAlign:"right",fontWeight:800}}>TOTAL BOQ</td><td style={{...ui.td,fontWeight:800}}>{money(boqTotal)}</td></tr></tbody></table></TableWrap></section>
      <section style={ui.card}><h2 style={{marginTop:0}}>Reports 5 & 6 — Development Cost and Revenue / Profit Analysis</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:14}}><TableWrap><table style={ui.table}><tbody>{[["Land Purchase Cost",landPurchase],["Development Cost",developmentCost],["Amenity Cost",amenityCost],["Approval / Legal Cost (2.5%)",approval],[`Contingency (${generated.contingencyPct}%)`,contingency],["Total Project Cost",totalCost]].map(([k,v])=><tr key={String(k)}><td style={ui.td}>{k}</td><td style={{...ui.td,fontWeight:800}}>{money(Number(v))}</td></tr>)}</tbody></table></TableWrap><TableWrap><table style={ui.table}><tbody>{[["Saleable Area",num(layout.saleableArea)+" sqft"],["Revenue",money(revenue)],["Gross Profit",money(grossProfit)],["Net Profit",money(netProfit)],["Profit %",(totalCost?num(netProfit/totalCost*100,2):"0")+"%"],["Profit per Plot",money(layout.plots.length?netProfit/layout.plots.length:0)]].map(([k,v])=><tr key={String(k)}><td style={ui.td}>{k}</td><td style={{...ui.td,fontWeight:800}}>{v}</td></tr>)}</tbody></table></TableWrap></div></section>
    </>}
    <footer style={{padding:14,textAlign:"center",fontSize:10,color:"#64748b"}}>Concept planning only. Final layout, road standards, amenity reservations and approvals must be verified by a licensed town planner and competent authority.</footer>
  </main>;
}
